import React, { useState, useEffect, useRef, useCallback } from "react";
import { View, Text, Linking, ActivityIndicator, FlatList, Animated } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import * as FileSystem from "expo-file-system/legacy";
import { activateKeepAwakeAsync, deactivateKeepAwake } from "expo-keep-awake";
import { storageHelper, storage } from "../utils/storage";
import { useThemeColors } from "../theme/useThemeColors";
import { usePlaybackStore } from "../store/usePlaybackStore";
import { showAppDialog } from "../store/useDialogStore";
import Icon from "../components/Icon";
import ErrorState from "../components/ErrorState";
import { api } from "../utils/api";
import { queueEbookProgressPatch, reconcileLinkedProgress } from "../utils/progressSync";
import { useUserStore } from "../store/useUserStore";
import { useDownloadStore } from "../store/useDownloadStore";
import { FOLIATE_BUNDLE } from "../utils/foliateBundle";
import BottomSheet from "../components/BottomSheet";
import Pressable from "../components/HintPressable";
import { resolveAudioTarget, audioPositionForReadingFraction, approximateClock } from "../utils/formatSwitch";

// Height of the collapsed mini player (mirrors PlayerBottomSheet MINIPLAYER_HEIGHT)
// so reader content can reserve space and not sit underneath it.
const MINIPLAYER_HEIGHT = 68;

// Defensive native-module imports so a build without them can't crash the app.
let Pdf: any = null;
try { Pdf = require("react-native-pdf").default; } catch (e) { Pdf = null; }
let WebView: any = null;
try { WebView = require("react-native-webview").WebView; } catch (e) { WebView = null; }
let Sharing: any = null;
try { Sharing = require("expo-sharing"); } catch (e) { Sharing = null; }

// Cap for inlining the ebook as base64 into the WebView. Most ebooks are 1–5MB;
// beyond this the bridge transfer gets heavy, so we offer "open externally".
const MAX_EBOOK_INLINE_BYTES = 12 * 1024 * 1024;

// Text-size stepper bounds (percent of the publisher's base size).
const FONT_SIZE_MIN = 80;
const FONT_SIZE_MAX = 180;

// foliate-js is VENDORED (utils/foliateBundle.ts, generated by
// scripts/build-foliate-bundle.mjs) and inlined into the reader HTML below, so
// the ebook reader renders fully OFFLINE — no jsdelivr CDN at read time.

// Builds the foliate-js reader HTML. The book bytes are passed in as base64
// so no CORS/auth request happens in the WebView. Themed to the app surface,
// paginated, with swipe + tap-to-turn gestures and animated page transitions;
// progress is reported back to RN via postMessage.
function ebookHtml(
  base64: string,
  bg: string,
  fg: string,
  accent: string,
  startCfi: string,
  mimeHint: string,
  fontSize: number,
  fontFamily: string,
  lineHeight: number,
  pageCurl: boolean
): string {
  // Compute the filename extension for foliate-js format detection
  const ext = mimeHint === "application/epub+zip" ? ".epub" : mimeHint === "application/x-mobipocket-ebook" ? ".mobi" : ".azw3";
  return `<!DOCTYPE html><html><head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  html,body{margin:0;padding:0;height:100%;background:${bg};overflow:hidden;}
  foliate-view{height:100%;width:100%;}
  #msg{position:absolute;top:0;left:0;right:0;bottom:0;display:flex;align-items:center;justify-content:center;
    color:${fg};font-family:sans-serif;padding:24px;text-align:center;z-index:10;}
</style>
<style id="reader-margins">
  foliate-view::part(head) {
    height: 16px !important;
    min-height: 16px !important;
  }
  foliate-view::part(foot) {
    height: 16px !important;
    min-height: 16px !important;
  }
</style>
</head><body>
<div id="msg">Loading…</div>
<script>
  // Polyfills for foliate-js on OLDER Android System WebViews. foliate-js
  // uses Object.groupBy / Map.groupBy (Chrome 117+, late 2023); many devices
  // run an older, non-auto-updating System WebView, where the reader would
  // otherwise fail with "Object.groupBy is not a function". Must run BEFORE
  // the foliate module below (classic script executes first).
  (function(){
    function groupByInto(make, get, set, items, cb){
      var res = make(), i = 0;
      for (var it of items){ var k = cb(it, i++); var a = get(res, k); if (a) a.push(it); else set(res, k, [it]); }
      return res;
    }
    if (typeof Object.groupBy !== 'function') {
      Object.groupBy = function(items, cb){
        return groupByInto(function(){return Object.create(null);},
          function(o,k){return o[k];}, function(o,k,v){o[k]=v;}, items, cb);
      };
    }
    if (typeof Map.groupBy !== 'function') {
      Map.groupBy = function(items, cb){
        return groupByInto(function(){return new Map();},
          function(m,k){return m.get(k);}, function(m,k,v){m.set(k,v);}, items, cb);
      };
    }
  })();
</script>
<script type="module">
  // Vendored foliate-js, inlined (no network). Registers the <foliate-view>
  // custom element as a side effect; inline module scripts avoid the file://
  // CORS wall that blocks external module imports in Android WebView.
${FOLIATE_BUNDLE}

  const bg = "${bg}";
  const fg = "${fg}";
  const accent = "${accent}";

  function post(o){ try{ window.ReactNativeWebView.postMessage(JSON.stringify(o)); }catch(e){} }

  // Decode base64 to a File/Blob for foliate-js
  function base64ToFile(b64, name) {
    var bin = atob(b64);
    var len = bin.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
    return new File([bytes], name, { type: "${mimeHint}" });
  }

  async function init() {
    try {
      while (window.innerWidth === 0 || window.innerHeight === 0) {
        await new Promise(resolve => setTimeout(resolve, 50));
      }
      var file = base64ToFile("${base64}", "book${ext}");
      var view = document.createElement('foliate-view');
      view.setAttribute('margin', '16px');
      document.body.append(view);

      // Apply reading styles — theme colors and typography
      var fontValue = "${fontFamily}" === "serif" ? "Georgia, serif" : "system-ui, sans-serif";
      var readerCSS = \`
        @namespace epub "http://www.idpf.org/2007/ops";
        html { color-scheme: light dark; }
        body {
          background: \${bg} !important;
          color: \${fg} !important;
          font-size: ${fontSize}% !important;
          text-align: start;
          -webkit-hyphens: auto;
          hyphens: auto;
        }
        body, p, li, blockquote, dd, div, span, a {
          font-family: \${fontValue} !important;
          line-height: ${lineHeight} !important;
        }
        pre { white-space: pre-wrap !important; }
      \`;
      view.addEventListener('load', e => {
        e.detail?.doc?.documentElement?.setAttribute?.('style',
          'background:' + bg + ' !important; color:' + fg + ' !important;');
      });

      // Track relocations — report progress back to React Native
      view.addEventListener('relocate', e => {
        var detail = e.detail;
        if (detail) {
          post({
            type: 'location',
            cfi: detail.cfi || '',
            fraction: detail.fraction || 0,
            section: detail.section || 0,
            page: (view.renderer.page || 0) + 1,
            pages: view.renderer.pages || 1,
            tocItem: detail.tocItem ? { label: detail.tocItem.label || '' } : null,
          });
        }
      });

      await view.open(file);
      document.getElementById('msg').style.display = 'none';

      // Send TOC back to React Native
      post({
        type: 'toc',
        toc: view.book.toc || []
      });

      // Apply styles after opening
      view.renderer.setStyles?.(readerCSS);

      // Restore saved position. JSON.stringify escapes the CFI — a stored or
      // server value containing a quote/backslash/newline would otherwise
      // break (or inject into) this generated script.
      var startCfi = ${startCfi ? JSON.stringify(String(startCfi)) : "null"};
      if (startCfi) {
        try { await view.goTo(startCfi); } catch(e) {}
      } else {
        try { await view.goTo(0); } catch(e) {}
      }

      // Expose navigation functions for RN injection and gesture handling
      window.goNext = () => { try { view.goRight(); } catch(e) {} };
      window.goPrev = () => { try { view.goLeft(); } catch(e) {} };
      window.goToHref = (href) => { try { view.goTo(href); } catch(e) {} };
      // Fraction navigation for the player's "Read from here" jump (percent
      // format switching) — called from RN via injectJavaScript after 'ready'.
      window.goToFraction = (f) => { try { view.goToFraction(f); } catch(e) {} };
      window.setReaderStyles = (css) => { try { view.renderer.setStyles(css); } catch(e) {} };

      // ---- Page-turn gestures: finger-follow curl + tap/swipe fallback ----
      // When the curl is enabled the page tracks your finger and peels with a
      // soft fold shadow, completing (or snapping back) on release. When it's
      // off — or the OS asks for reduced motion — we keep the original discrete
      // tap-zone / swipe behavior. The curl is a CSS transform on the foliate
      // host + a gradient overlay at the fold; no snapshotting, so it can't get
      // out of sync with the rendered content.
      var curlEnabled = ${pageCurl ? "true" : "false"};
      try {
        if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) curlEnabled = false;
      } catch(e) {}
      // Let RN flip it live (settings toggle) without reloading the book.
      window.setPageCurl = function(v){ curlEnabled = !!v; };

      var W = function(){ return window.innerWidth || 360; };
      var TURN_MS = 200;
      var drag = { active:false, decided:false, dir:0, sx:0, sy:0, st:0, animating:false };

      // Fold shadow that tracks the lifting page edge.
      var curlEl = document.createElement('div');
      curlEl.id = 'pagecurl';
      curlEl.style.cssText = 'position:fixed;top:0;bottom:0;width:56px;pointer-events:none;z-index:9;opacity:0;transition:opacity .12s;';
      document.body.appendChild(curlEl);

      function setPageX(px){ view.style.transform = px ? 'translateX(' + px + 'px)' : ''; }
      function showCurl(px, progress){
        var w = W();
        var a = Math.min(0.38, 0.12 + progress * 0.32);
        if (drag.dir < 0) {
          var fold = w + px; // page moved left; fold at its right edge
          curlEl.style.left = Math.max(-56, fold - 8) + 'px';
          curlEl.style.background = 'linear-gradient(to right, rgba(0,0,0,' + a + '), rgba(0,0,0,0) 70%)';
        } else {
          curlEl.style.left = Math.min(w, px - 48) + 'px';
          curlEl.style.background = 'linear-gradient(to left, rgba(0,0,0,' + a + '), rgba(0,0,0,0) 70%)';
        }
        curlEl.style.opacity = '1';
      }
      function hideCurl(){ curlEl.style.opacity = '0'; }

      // Slide the current page fully off in the turn direction, then swap to the
      // neighbor and reset. The uncovered strip is the page-colored background,
      // reading as the blank margin of a turning leaf.
      function finishTurn(dir){
        if (drag.animating) return;
        drag.animating = true;
        var w = W();
        view.style.transition = 'transform ' + TURN_MS + 'ms ease-out';
        setPageX(dir < 0 ? -w : w);
        hideCurl();
        setTimeout(function(){
          view.style.transition = '';
          setPageX(0);
          try { if (dir < 0) window.goNext(); else window.goPrev(); } catch(e) {}
          drag.animating = false;
        }, TURN_MS);
      }
      function snapBack(){
        drag.animating = true;
        view.style.transition = 'transform 160ms ease-out';
        setPageX(0);
        hideCurl();
        setTimeout(function(){ view.style.transition = ''; drag.animating = false; }, 170);
      }
      // Discrete turn honoring the current mode (animated when the curl is on).
      function turn(dir){ if (curlEnabled) finishTurn(dir); else if (dir < 0) window.goNext(); else window.goPrev(); }

      document.addEventListener('touchstart', function(e){
        if (drag.animating) return;
        var t = e.changedTouches[0];
        drag.active = true; drag.decided = false; drag.dir = 0;
        drag.sx = t.clientX; drag.sy = t.clientY; drag.st = Date.now();
      }, { passive: true });

      document.addEventListener('touchmove', function(e){
        if (!drag.active || drag.animating || !curlEnabled) return;
        var t = e.changedTouches[0];
        var dx = t.clientX - drag.sx, dy = t.clientY - drag.sy;
        if (!drag.decided) {
          if (Math.abs(dx) < 8 && Math.abs(dy) < 8) return;
          // Vertical / long-press-drag (text selection) → not a page turn.
          if (Math.abs(dx) <= Math.abs(dy) * 1.2) { drag.active = false; return; }
          drag.decided = true; drag.dir = dx < 0 ? -1 : 1;
        }
        setPageX(dx);
        showCurl(dx, Math.min(1, Math.abs(dx) / W()));
        if (e.cancelable) e.preventDefault();
      }, { passive: false });

      document.addEventListener('touchend', function(e){
        var t = e.changedTouches[0];
        var dx = t.clientX - drag.sx, dy = t.clientY - drag.sy, dt = Date.now() - drag.st;
        var wasDrag = drag.decided;
        drag.active = false; drag.decided = false;
        if (drag.animating) return;
        if (wasDrag) {
          var progress = Math.abs(dx) / W();
          var fast = dt < 250 && Math.abs(dx) > 60;
          if (progress > 0.25 || fast) finishTurn(drag.dir); else snapBack();
          return;
        }
        var w = W();
        if (Math.abs(dx) > 40 && Math.abs(dx) > Math.abs(dy) * 1.2 && dt < 700) {
          turn(dx < 0 ? -1 : 1);
        } else if (Math.abs(dx) < 10 && Math.abs(dy) < 10 && dt < 300) {
          if (t.clientX < w * 0.3) turn(1);
          else if (t.clientX > w * 0.7) turn(-1);
        }
      }, { passive: true });

      // Keyboard navigation
      document.addEventListener('keyup', function(e) {
        if (e.key === 'ArrowRight') window.goNext();
        else if (e.key === 'ArrowLeft') window.goPrev();
      });

      post({ type: 'ready' });
    } catch (e) {
      document.getElementById('msg').innerText = 'Could not open this ebook: ' + e.message;
      post({ type: 'error', message: String(e) });
    }
  }
  init();
</script>
</body></html>`;
}

// Map file extensions to MIME types for foliate-js File constructor
function getMimeForFormat(format: string): string {
  switch (format) {
    case "epub": return "application/epub+zip";
    case "mobi": return "application/x-mobipocket-ebook";
    case "azw3": case "azw": case "kf8": return "application/x-mobipocket-ebook";
    default: return "application/octet-stream";
  }
}

// Map file extensions to expected filename suffixes for foliate-js format detection
function getExtForFormat(format: string): string {
  switch (format) {
    case "epub": return ".epub";
    case "mobi": return ".mobi";
    case "azw3": case "kf8": return ".azw3";
    case "azw": return ".azw";
    default: return "." + format;
  }
}

export default function ReaderScreen({ route, navigation }: any) {
  const colors = useThemeColors();
  const insets = useSafeAreaInsets();
  // Reading is a long touch-free activity — keep the screen awake, but only
  // while the reader is actually the FOCUSED screen. useKeepAwake() held the
  // lock for as long as the reader stayed mounted, so navigating forward from
  // it (leaving it in the stack) kept the screen on off-screen, draining the
  // battery. Activate on focus, release on blur AND unmount.
  const KEEP_AWAKE_TAG = "reader";
  useEffect(() => {
    let held = false;
    const activate = () => {
      if (held) return;
      held = true;
      // Wrapped: the async activator may return void in some environments.
      Promise.resolve(activateKeepAwakeAsync(KEEP_AWAKE_TAG)).catch(() => {});
    };
    const release = () => {
      if (!held) return;
      held = false;
      try {
        deactivateKeepAwake(KEEP_AWAKE_TAG);
      } catch {}
    };
    activate(); // focused on mount
    const unsubFocus = navigation?.addListener?.("focus", activate);
    const unsubBlur = navigation?.addListener?.("blur", release);
    return () => {
      release();
      unsubFocus?.();
      unsubBlur?.();
    };
  }, [navigation]);
  const hasSession = usePlaybackStore((s) => s.currentSession !== null);
  const { itemId, ebookFormat, title, initialFraction } = route.params || {};
  // One-shot "jump to fraction" from the player's Read-from-here handoff —
  // consumed on the WebView's 'ready' message, then cleared.
  const pendingJumpRef = useRef<number | null>(
    typeof initialFraction === "number" && Number.isFinite(initialFraction)
      ? Math.max(0, Math.min(1, initialFraction))
      : null
  );
  const [pdfError, setPdfError] = useState(false);
  // PDF page tracking: restore the last-read page and show a footer indicator,
  // mirroring what the epub path gets from foliate relocations. Controlled
  // page state so the footer prev/next buttons (a11y: PDF page turns are
  // otherwise scroll-only) can drive it and an in-place book change re-seeds it.
  const pdfPageKey = `pdfPage_${itemId}`;
  const [pdfPage, setPdfPage] = useState<number>(() => Math.max(1, storage.getNumber(pdfPageKey) || 1));
  const [pdfProgress, setPdfProgress] = useState<{ page: number; pages: number } | null>(null);
  // The last PDF position, flushed on unmount like latestProgressRef does for
  // epub — the debounced onPageChanged sync alone is cancelled by the cleanup
  // clearing syncTimeoutRef, losing a page turn made within ~2s of leaving.
  const latestPdfProgressRef = useRef<{ page: number; fraction: number } | null>(null);
  // In-place itemId changes update route params WITHOUT unmounting, so these
  // mount-seeded values must be re-seeded for the new book — the reseed lives in
  // an effect (see below, keyed on itemId) rather than during render, so the
  // previous book's flush effect can run its cleanup FIRST.
  // Bumped by the error-state Retry button to re-run the ebook load effect.
  const [reloadKey, setReloadKey] = useState(0);

  // Bottom reserve spacing matches exactly what the floating mini-player consumes.
  // When no session exists, the mini-player slides completely down (height = 0),
  // so we fall back to standard bottom safe inset for spacing.
  const bottomReserve = hasSession ? MINIPLAYER_HEIGHT + insets.bottom : insets.bottom;

  const serverConfig = storageHelper.getServerConfig();
  const serverAddress = serverConfig?.address?.replace(/\/$/, "") || "";
  const token = serverConfig?.token || "";
  const ebookUri = itemId && serverAddress ? `${serverAddress}/api/items/${itemId}/ebook?token=${token}` : "";

  const format = String(ebookFormat || "").replace(/^\./, "").toLowerCase();
  const isPdf = format === "pdf" || (!format && !!ebookUri);
  // foliate-js supports epub, mobi, azw3, azw, kf8
  const isFoliateFormat = ["epub", "mobi", "azw3", "azw", "kf8"].includes(format);
  const isShareOnly = !isPdf && !isFoliateFormat;

  // --- Ebook settings & state (EPUB / MOBI / AZW3) ---
  const [ebookFileUri, setEbookFileUri] = useState<string | null>(null);
  const [ebookStatus, setEbookStatus] = useState<"idle" | "loading" | "ready" | "error" | "toobig">("idle");
  // Why the ebook failed (download vs foliate parse) — shown small on the
  // error screen so a failure is actionable instead of a generic "try again".
  const [ebookError, setEbookError] = useState<string>("");
  const webRef = useRef<any>(null);
  const progressKey = `ebookCfi_${itemId}`;
  const syncTimeoutRef = useRef<any>(null);
  const latestProgressRef = useRef<{ cfi: string; fraction: number } | null>(null);

  // Pulsing animation for loading state
  const pulseAnim = useRef(new Animated.Value(0.6)).current;
  useEffect(() => {
    let anim: Animated.CompositeAnimation | null = null;
    if (ebookStatus === "loading" || ebookStatus === "idle") {
      anim = Animated.loop(
        Animated.sequence([
          Animated.timing(pulseAnim, {
            toValue: 1.0,
            duration: 1000,
            useNativeDriver: true,
          }),
          Animated.timing(pulseAnim, {
            toValue: 0.6,
            duration: 1000,
            useNativeDriver: true,
          }),
        ])
      );
      anim.start();
    } else {
      pulseAnim.setValue(0.6);
    }
    return () => {
      if (anim) anim.stop();
    };
  }, [ebookStatus, pulseAnim]);

  // Style Settings States
  const [fontSize, setFontSize] = useState(() => storage.getNumber("reader_font_size") || 100);
  const [fontFamily, setFontFamily] = useState<"serif" | "sans-serif">(() => (storage.getString("reader_font_family") as any) || "serif");
  const [lineHeight, setLineHeight] = useState(() => storage.getNumber("reader_line_height") || 1.5);
  // Finger-follow page-curl turn animation. Defaults on; persisted so it's a
  // one-time choice. `getBoolean` returns undefined until first set, so treat
  // undefined as the default (true).
  const [pageCurl, setPageCurl] = useState<boolean>(() => {
    const v = storage.getBoolean("reader_page_curl");
    return v === undefined ? true : v;
  });

  // TOC and Progress Info States
  const [toc, setToc] = useState<any[]>([]);
  const [showToc, setShowToc] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [pageProgress, setPageProgress] = useState<{
    page: number;
    pages: number;
    fraction: number;
    tocItem: { label: string } | null;
  } | null>(null);

  const bg = colors.surface;
  const fg = colors.onSurface;
  const accent = colors.primary;

  // Dynamically push styles to the reader WebView when text settings change
  useEffect(() => {
    storage.set("reader_font_size", fontSize);
    storage.set("reader_font_family", fontFamily);
    storage.set("reader_line_height", lineHeight);

    if (ebookStatus === "ready" && webRef.current) {
      const fontValue = fontFamily === "serif" ? "Georgia, serif" : "system-ui, sans-serif";
      const css = `
        @namespace epub "http://www.idpf.org/2007/ops";
        html { color-scheme: light dark; }
        body {
          background: ${bg} !important;
          color: ${fg} !important;
          font-size: ${fontSize}% !important;
          text-align: start;
          -webkit-hyphens: auto;
          hyphens: auto;
        }
        body, p, li, blockquote, dd, div, span, a {
          font-family: ${fontValue} !important;
          line-height: ${lineHeight} !important;
        }
        pre { white-space: pre-wrap !important; }
      `;
      // Clean script to inject
      const cleanCSS = css.replace(/`/g, "\\`").replace(/\n/g, "");
      webRef.current.injectJavaScript(`window.setReaderStyles && window.setReaderStyles(\`${cleanCSS}\`);true;`);
    }
  }, [fontSize, fontFamily, lineHeight, ebookStatus, bg, fg, accent]);

  // Persist the page-curl preference and flip it live in the WebView (no reload).
  useEffect(() => {
    storage.set("reader_page_curl", pageCurl);
    if (ebookStatus === "ready" && webRef.current) {
      webRef.current.injectJavaScript(
        `window.setPageCurl && window.setPageCurl(${pageCurl ? "true" : "false"});true;`
      );
    }
  }, [pageCurl, ebookStatus]);

  useEffect(() => {
    if (itemId) {
      storage.set(`last_interaction_${itemId}`, "read");
    }
  }, [itemId]);

  // True once the screen is torn down — late WebView messages must not
  // re-arm the sync debounce (the cleanup below already ran).
  const unmountedRef = useRef(false);

  // Sync pending ebook progress to server on unmount/screen change
  useEffect(() => {
    // Re-arm on an IN-PLACE itemId change: navigate("Reader", {itemId: B})
    // from inside the reader updates params without unmounting, so the
    // previous run's cleanup set unmountedRef true — without this reset,
    // every message for the NEW book was dropped (no saves at all).
    unmountedRef.current = false;
    return () => {
      unmountedRef.current = true;
      if (syncTimeoutRef.current) {
        clearTimeout(syncTimeoutRef.current);
      }
      if (latestProgressRef.current) {
        const { cfi, fraction } = latestProgressRef.current;
        console.log("[Reader] Unmounting, flushing ebook progress to server:", itemId, cfi, fraction);
        // ONLY the ebook fields (matches the ABS web reader). Sending
        // `progress`/`isFinished` here would clobber the AUDIO progress on
        // both-format items — e.g. opening the ebook of a book you finished
        // in audio would un-finish it.
        api.patch(`/api/me/progress/${itemId}`, {
          ebookLocation: cfi,
          ebookProgress: fraction,
          // One-way: mark finished when the book is done reading, but never
          // send isFinished:false (that would un-finish audio-finished items).
          ...(fraction >= 0.99 ? { isFinished: true } : {}),
        }).catch((e) => {
          console.warn("[Reader] Failed to sync ebook progress on unmount:", e);
          // Offline (downloaded ebook) — queue so the cfi still reaches the
          // server (and Storyteller/other devices) when connectivity returns.
          queueEbookProgressPatch(itemId, cfi, fraction, fraction >= 0.99);
        });
        // LOCK: the reader for this item just flushed its final reading
        // position — if the user linked its progresses, pull the AUDIO up to
        // this reading fraction (furthest-wins, fraction-only; see
        // reconcileLinkedProgress). No-op unless locked.
        try {
          reconcileLinkedProgress(itemId, { ebookFraction: fraction });
        } catch {}
        // The snapshot belongs to THIS itemId. Clearing it stops an in-place
        // book change from flushing book A's cfi onto book B's server record
        // (which could even one-way auto-finish B).
        latestProgressRef.current = null;
      }
      // PDF equivalent of the epub flush above: the debounced onPageChanged
      // sync is cancelled by clearing syncTimeoutRef, so flush the last page.
      if (latestPdfProgressRef.current) {
        const { page, fraction } = latestPdfProgressRef.current;
        api
          .patch(`/api/me/progress/${itemId}`, {
            ebookLocation: String(page),
            ebookProgress: fraction,
            ...(fraction >= 0.99 ? { isFinished: true } : {}),
          })
          .catch(() => queueEbookProgressPatch(itemId, String(page), fraction, fraction >= 0.99));
        // LOCK: reconcile the audio up to this reading fraction when linked
        // (fraction-only, furthest-wins). No-op unless locked.
        try {
          reconcileLinkedProgress(itemId, { ebookFraction: fraction });
        } catch {}
        latestPdfProgressRef.current = null;
      }
    };
  }, [itemId]);

  // Re-seed the per-book PDF state when the itemId changes IN PLACE (route
  // params swap without an unmount). Keyed on [itemId] and defined AFTER the
  // flush effect above so, on a change, React runs that effect's cleanup FIRST
  // (flushing book A's last page) before this clears latestPdfProgressRef and
  // seeds book B — moving it out of the render body also removes the
  // setState-during-render anti-pattern. Skips the mount run: the useState/
  // useRef initializers already seed the first book.
  const readerReseededRef = useRef(false);
  useEffect(() => {
    if (!readerReseededRef.current) {
      readerReseededRef.current = true;
      return;
    }
    setPdfPage(Math.max(1, storage.getNumber(pdfPageKey) || 1));
    latestPdfProgressRef.current = null;
    pendingJumpRef.current =
      typeof initialFraction === "number" && Number.isFinite(initialFraction)
        ? Math.max(0, Math.min(1, initialFraction))
        : null;
  }, [itemId]);

  // Load ebook contents and generate the HTML wrapper
  useEffect(() => {
    if (!isFoliateFormat || !WebView || !ebookUri) return;
    setEbookFileUri(null);
    setEbookStatus("loading");
    let cancelled = false;
    (async () => {
      try {
        const localDownload = useDownloadStore.getState().completedDownloads[itemId];
        const ebookPart = localDownload?.parts?.find(p => p.id === "ebook");
        
        let fileUri = "";
        if (ebookPart?.localFilePath) {
          fileUri = ebookPart.localFilePath;
          console.log("[Reader] Loading ebook from offline download:", fileUri);
        } else {
          const ext = getExtForFormat(format);
          const localPath = `${FileSystem.cacheDirectory}reader_${itemId}${ext}`;
          const dl = await FileSystem.downloadAsync(ebookUri, localPath, {
            headers: { Authorization: `Bearer ${token}` },
          });
          fileUri = dl.uri;
        }

        const info = await FileSystem.getInfoAsync(fileUri);
        if ((info as any).size && (info as any).size > MAX_EBOOK_INLINE_BYTES) {
          if (!ebookPart?.localFilePath) {
            FileSystem.deleteAsync(fileUri, { idempotent: true }).catch(() => {});
          }
          if (!cancelled) setEbookStatus("toobig");
          return;
        }
        const base64 = await FileSystem.readAsStringAsync(fileUri, {
          encoding: FileSystem.EncodingType.Base64,
        });
        if (!ebookPart?.localFilePath) {
          FileSystem.deleteAsync(fileUri, { idempotent: true }).catch(() => {});
        }
        if (cancelled) return;
        // Restore position: local (MMKV) vs server ebookLocation — prefer the
        // FRESHER one, so reading ahead on another device isn't lost to a stale
        // local cfi. The local save timestamp is written alongside every cfi in
        // onWebMessage; the server side uses the progress entry's lastUpdate.
        // Caveat (accepted): lastUpdate also bumps on audio-only syncs, but the
        // reader mirrors every cfi to the server too, so when nobody else read
        // further the two cfis match and the choice is moot.
        const localCfi = storage.getString(progressKey) || "";
        const localCfiAt = storage.getNumber(`${progressKey}_at`) || 0;
        const serverProgress = useUserStore.getState().mediaProgress[itemId];
        const serverCfi = serverProgress?.ebookLocation || "";
        const serverCfiAt = Number(serverProgress?.lastUpdate || serverProgress?.updatedAt || 0);
        const savedCfi =
          serverCfi && serverCfi !== localCfi && serverCfiAt > localCfiAt
            ? serverCfi
            : localCfi || serverCfi;

        const mime = getMimeForFormat(format);
        const htmlContent = ebookHtml(base64, bg, fg, accent, savedCfi, mime, fontSize, fontFamily, lineHeight, pageCurl);
        const htmlPath = `${FileSystem.cacheDirectory}reader_${itemId}.html`;
        await FileSystem.writeAsStringAsync(htmlPath, htmlContent, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        if (cancelled) return;
        setEbookFileUri(htmlPath);
        setEbookStatus("ready");
      } catch (e: any) {
        console.warn("[Reader] ebook load failed", e);
        if (!cancelled) {
          setEbookError(`load: ${e?.message || String(e)}`);
          setEbookStatus("error");
        }
      }
    })();
    return () => { cancelled = true; };
  }, [isFoliateFormat, ebookUri, reloadKey]);

  const onWebMessage = useCallback((event: any) => {
    try {
      if (unmountedRef.current) return;
      const data = JSON.parse(event.nativeEvent.data);
      if (data.type === "location") {
        // Sanitize at the trust boundary: foliate/webview payloads can carry
        // out-of-range fractions (a fraction of 2 would ONE-WAY auto-finish
        // the book server-side) and non-string cfis (unrecoverable MMKV
        // writes).
        const rawFraction = Number(data.fraction);
        data.fraction = Number.isFinite(rawFraction) ? Math.min(1, Math.max(0, rawFraction)) : 0;
        if (typeof data.cfi !== "string") data.cfi = "";
        if (data.cfi) {
          storage.set(progressKey, data.cfi);
          // Save-time timestamp so the restore logic can compare local vs
          // server freshness (see the load effect above).
          storage.set(`${progressKey}_at`, Date.now());
          latestProgressRef.current = { cfi: data.cfi, fraction: data.fraction || 0 };
        }
        setPageProgress({
          page: data.page || 1,
          pages: data.pages || 1,
          fraction: data.fraction || 0,
          tocItem: data.tocItem || null,
        });

        // Update local store progress state instantly — EBOOK fields only.
        // Touching `progress`/`isFinished` here would clobber the audio
        // progress on both-format items (and un-finish finished audiobooks).
        const updatedProgress = {
          libraryItemId: itemId,
          ebookLocation: data.cfi || "",
          ebookProgress: data.fraction || 0,
          updatedAt: Date.now(),
        };
        useUserStore.setState({
          mediaProgress: {
            ...useUserStore.getState().mediaProgress,
            [itemId]: {
              ...useUserStore.getState().mediaProgress[itemId],
              ...updatedProgress,
            },
          },
        });

        // Debounce progress PATCH to server (ebook fields only, matching the
        // ABS web reader).
        if (syncTimeoutRef.current) {
          clearTimeout(syncTimeoutRef.current);
        }
        syncTimeoutRef.current = setTimeout(async () => {
          try {
            await api.patch(`/api/me/progress/${itemId}`, {
              ebookLocation: data.cfi || "",
              ebookProgress: data.fraction || 0,
              ...((data.fraction || 0) >= 0.99 ? { isFinished: true } : {}),
            });
          } catch (e) {
            console.warn("[Reader] Failed to sync ebook progress:", e);
            // Offline — queue (ebook fields only) instead of dropping it.
            queueEbookProgressPatch(
              itemId,
              data.cfi || "",
              data.fraction || 0,
              (data.fraction || 0) >= 0.99
            );
          }
        }, 2000);
      } else if (data.type === "toc") {
        setToc(data.toc || []);
      } else if (data.type === "ready") {
        // Player → reader handoff: jump to the mapped fraction once the book
        // is actually rendered (overrides the startCfi restore).
        const f = pendingJumpRef.current;
        if (f != null && webRef.current) {
          pendingJumpRef.current = null;
          webRef.current.injectJavaScript(
            `window.goToFraction && window.goToFraction(${Number(f)});true;`
          );
        }
      } else if (data.type === "error") {
        setEbookError(`render: ${data.message || "unknown"}`);
        setEbookStatus("error");
      }
    } catch {}
  }, [progressKey, itemId]);

  const openExternally = async () => {
    try {
      if (Sharing && (await Sharing.isAvailableAsync())) {
        // Downloaded book: share the local file directly — re-downloading
        // fails exactly when downloads matter (offline / "too large" books).
        const localEbook = useDownloadStore
          .getState()
          .completedDownloads[itemId]?.parts?.find((p: any) => p.id === "ebook")?.localFilePath;
        if (localEbook) {
          // localFilePath may be a bare absolute path (older/cached download
          // rows) — expo-sharing wants a URI (same normalization as the
          // playback store's local track resolution).
          const uri =
            localEbook.startsWith("file://") || localEbook.startsWith("content://")
              ? localEbook
              : `file://${localEbook}`;
          await Sharing.shareAsync(uri, { dialogTitle: title || "Open ebook" });
          return;
        }
        const localPath = `${FileSystem.cacheDirectory}book_${itemId}.${format || "bin"}`;
        const dl = await FileSystem.downloadAsync(ebookUri, localPath, {
          headers: { Authorization: `Bearer ${token}` },
        });
        await Sharing.shareAsync(dl.uri, { dialogTitle: title || "Open ebook" });
        return;
      }
    } catch (e) {
      console.warn("[Reader] share failed", e);
    }
    if (ebookUri) Linking.openURL(ebookUri).catch(() => {});
  };

  // "Listen from here": start the audiobook edition at (approximately) the
  // current reading position — the reader-side Whispersync entry point
  // (player-side lives in PlayerBottomSheet's Read-from-here).
  const listenFromHere = () => {
    (async () => {
      const target = await resolveAudioTarget(itemId);
      if (!target) {
        showAppDialog({ title: "No audiobook available", message: "This book doesn't have an audio edition in your library." });
        return;
      }
      const fraction = isPdf
        ? (pdfProgress ? pdfProgress.page / Math.max(1, pdfProgress.pages) : 0)
        : latestProgressRef.current?.fraction ?? pageProgress?.fraction ?? 0;
      const estimate = target.duration
        ? ` at about ${approximateClock(audioPositionForReadingFraction(fraction, target.duration))}`
        : "";
      showAppDialog({
        title: "Listen from here?",
        message: `Start the audiobook${estimate}? Position matching is approximate.`,
        buttons: [
        { text: "Cancel", style: "cancel" },
        {
          text: "Listen",
          onPress: () => {
            (async () => {
              try {
                const ok = await usePlaybackStore.getState().startPlayback(target.itemId);
                if (!ok) throw new Error("start failed");
                // Seek against the LIVE duration — the resolver's metadata
                // duration is display-grade only.
                const live = usePlaybackStore.getState();
                const dur = live.duration || target.duration || 0;
                if (dur > 0) await live.seek(audioPositionForReadingFraction(fraction, dur));
                navigation.goBack();
              } catch (e) {
                console.warn("[Reader] listen-from-here failed", e);
                showAppDialog({ title: "Couldn't start playback", message: "Check your connection to the server and try again." });
              }
            })();
          },
        },
      ],
      });
    })();
  };

  const selectTocItem = (href: string) => {
    // href comes from the EBOOK's own TOC via the bridge — untrusted. Escape
    // like startCfi (JSON.stringify): raw interpolation both broke navigation
    // for titles with quotes AND let a crafted epub execute arbitrary JS in
    // the reader WebView, which holds the native bridge.
    if (typeof href !== "string" || !href) return;
    if (webRef.current) {
      webRef.current.injectJavaScript(
        `window.goToHref && window.goToHref(${JSON.stringify(String(href))});true;`
      );
      setShowToc(false);
    }
  };

  const canRenderPdf = Pdf !== null && isPdf && !pdfError && !!ebookUri;
  const canRenderEbook = WebView !== null && isFoliateFormat && ebookStatus === "ready" && !!ebookFileUri;

  const formatLabel = format ? format.toUpperCase() : "ebook";

  const Header = (
    <View style={{ flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingTop: 8, paddingBottom: 8 }}>
      <Pressable
        onPress={() => navigation.goBack()}
        style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
        hitSlop={8}
        accessibilityRole="button"
        accessibilityLabel="Close reader"
      >
        <Icon name="back" size={24} color={colors.onSurface} />
      </Pressable>
      <Text numberOfLines={1} style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700", marginLeft: 4, flex: 1 }}>
        {title || "Reader"}
      </Text>
      {(isFoliateFormat && canRenderEbook) || canRenderPdf ? (
        <Pressable
          onPress={listenFromHere}
          style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
          hitSlop={8}
          accessibilityRole="button"
          accessibilityLabel="Listen from here"
        >
          <Icon name="headphones" size={24} color={colors.onSurface} />
        </Pressable>
      ) : null}
      {isFoliateFormat && canRenderEbook ? (
        <View style={{ flexDirection: "row", alignItems: "center", columnGap: 4 }}>
          <Pressable
            onPress={() => setShowToc(true)}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
            hitSlop={8}
            accessibilityRole="button"
            accessibilityLabel="Table of contents"
          >
            <Icon name="list" size={24} color={colors.onSurface} />
          </Pressable>
          <Pressable
            onPress={() => setShowSettings(true)}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
            hitSlop={8}
            accessibilityRole="button"
            accessibilityLabel="Reading settings"
          >
            <Icon name="settings" size={24} color={colors.onSurface} />
          </Pressable>
        </View>
      ) : null}
    </View>
  );

  const Fallback = ({
    message,
    showShare = true,
    onRetry,
  }: {
    message: string;
    showShare?: boolean;
    onRetry?: () => void;
  }) => (
    // Shared ErrorState treatment, but this is a book-open failure so it keeps
    // the "book" glyph and its dual Try-again / Open-externally actions.
    <ErrorState
      style={{ flex: 1 }}
      icon="book"
      title="Can't open this book"
      message={message}
      action={
        <View style={{ alignItems: "center" }}>
          {onRetry ? (
            <Pressable
              onPress={onRetry}
              accessibilityRole="button"
              style={{
                backgroundColor: colors.primary, paddingHorizontal: 24, height: 48, borderRadius: 24,
                alignItems: "center", justifyContent: "center", flexDirection: "row", marginBottom: 12,
              }}
            >
              <Icon name="refresh" size={20} color={colors.onPrimary} />
              <Text style={{ color: colors.onPrimary, fontSize: 15, fontWeight: "600", marginLeft: 8 }}>
                Try again
              </Text>
            </Pressable>
          ) : null}
          {showShare ? (
            <Pressable
              onPress={openExternally}
              accessibilityRole="button"
              style={{
                // Secondary action when Retry is present, primary otherwise.
                backgroundColor: onRetry ? colors.secondaryContainer : colors.primary,
                paddingHorizontal: 24, height: 48, borderRadius: 24,
                alignItems: "center", justifyContent: "center", flexDirection: "row",
              }}
            >
              <Icon name="share" size={20} color={onRetry ? colors.onSecondaryContainer : colors.onPrimary} />
              <Text
                style={{
                  color: onRetry ? colors.onSecondaryContainer : colors.onPrimary,
                  fontSize: 15, fontWeight: "600", marginLeft: 8,
                }}
              >
                Open in another app
              </Text>
            </Pressable>
          ) : null}
        </View>
      }
    />
  );

  // Recursive rendering helper for TOC hierarchical lists (subitems).
  // The section currently being read (foliate reports it on every relocate)
  // is tinted primary so long TOCs are scannable for "where am I".
  const currentTocLabel = pageProgress?.tocItem?.label || null;
  const renderTocItem = ({ item }: { item: any }) => {
    // Trust boundary: a malformed TOC (object label, string subitems) came
    // straight from the WebView and hard-crashed this renderer.
    const label = typeof item?.label === "string" && item.label ? item.label : "Untitled Section";
    const subitems = Array.isArray(item?.subitems) ? item.subitems : [];
    const isCurrent = !!currentTocLabel && label === currentTocLabel;
    return (
      <View style={{ marginLeft: 8 }}>
        <Pressable
          onPress={() => selectTocItem(item.href)}
          accessibilityRole="button"
          accessibilityLabel={label}
          accessibilityState={{ selected: isCurrent }}
          style={{
            paddingVertical: 14,
            paddingHorizontal: 16,
            borderBottomWidth: 1,
            borderBottomColor: colors.outlineVariant,
            flexDirection: "row",
            alignItems: "center",
          }}
        >
          <Text
            style={{
              flex: 1,
              color: isCurrent ? colors.primary : colors.onSurface,
              fontSize: 16,
              fontWeight: isCurrent ? "700" : "500",
            }}
          >
            {label}
          </Text>
          {isCurrent ? <Icon name="bookmark" size={18} color={colors.primary} /> : null}
        </Pressable>
        {subitems.length > 0 && (
          <View style={{ paddingLeft: 12, borderLeftWidth: 1, borderLeftColor: colors.outlineVariant }}>
            {subitems.map((sub: any, idx: number) => (
              <View key={idx}>
                {renderTocItem({ item: sub })}
              </View>
            ))}
          </View>
        )}
      </View>
    );
  };

  let body: React.ReactNode;
  if (canRenderPdf) {
    // Prefer the downloaded PDF file — the remote URL is dead exactly when
    // downloads matter (offline), which previously dead-ended a downloaded
    // PDF at the generic "can't be viewed" fallback.
    const localPdf = useDownloadStore
      .getState()
      .completedDownloads[itemId]?.parts?.find((p: any) => p.id === "ebook")?.localFilePath;
    body = (
      <Pdf
        // Remount for a new book so the controlled page starts fresh.
        key={itemId}
        source={
          localPdf
            ? { uri: localPdf }
            : { uri: ebookUri, headers: { Authorization: `Bearer ${token}` } }
        }
        style={{ flex: 1, backgroundColor: colors.surface }}
        page={pdfPage}
        onPageChanged={(page: number, numberOfPages: number) => {
          setPdfProgress({ page, pages: numberOfPages });
          // Keep the controlled page in sync with scroll (no-op jump when the
          // prop already equals the current page).
          setPdfPage((prev) => (prev !== page ? page : prev));
          // Remember where the user left off so reopening resumes here.
          storage.set(pdfPageKey, page);
          // PDFs get the SAME server sync the epub path has (ebook fields
          // only, matching the ABS web PDF reader: ebookLocation = page
          // number) — without it PDF progress never left the device: no
          // cross-device resume, no "Reading" row, no finish.
          const fraction = numberOfPages > 0 ? Math.min(1, page / numberOfPages) : 0;
          // Snapshot for the unmount flush (mirrors the epub latestProgressRef)
          // so a page turn within the debounce window still reaches the server.
          latestPdfProgressRef.current = { page, fraction };
          useUserStore.setState({
            mediaProgress: {
              ...useUserStore.getState().mediaProgress,
              [itemId]: {
                ...useUserStore.getState().mediaProgress[itemId],
                libraryItemId: itemId,
                ebookLocation: String(page),
                ebookProgress: fraction,
                updatedAt: Date.now(),
              },
            },
          });
          if (syncTimeoutRef.current) clearTimeout(syncTimeoutRef.current);
          syncTimeoutRef.current = setTimeout(async () => {
            try {
              await api.patch(`/api/me/progress/${itemId}`, {
                ebookLocation: String(page),
                ebookProgress: fraction,
                ...(fraction >= 0.99 ? { isFinished: true } : {}),
              });
            } catch (e) {
              console.warn("[Reader] Failed to sync PDF progress:", e);
              queueEbookProgressPatch(itemId, String(page), fraction, fraction >= 0.99);
            }
          }, 2000);
        }}
        onError={() => setPdfError(true)}
      />
    );
  } else if (isFoliateFormat) {
    if (!WebView) {
      // Native WebView module missing from this build — without this branch
      // the screen would sit on the loading state forever.
      body = <Fallback message="The in-app reader isn't available in this build. Open the ebook in another app instead." />;
    } else if (ebookStatus === "loading" || ebookStatus === "idle") {
      body = (
        <View style={{ flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }}>
          <Animated.View style={{ opacity: pulseAnim, transform: [{ scale: pulseAnim }], marginBottom: 20 }}>
            <View style={{
              width: 72, height: 72, borderRadius: 36, backgroundColor: colors.secondaryContainer,
              alignItems: "center", justifyContent: "center"
            }}>
              <Icon name="book" size={36} color={colors.primary} />
            </View>
          </Animated.View>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={{ color: colors.onSurface, fontSize: 16, fontWeight: "600", marginTop: 16 }}>
            Preparing your book…
          </Text>
          <Text style={{ color: colors.onSurfaceVariant, fontSize: 12, marginTop: 4 }}>
            Setting up typography and layout
          </Text>
        </View>
      );
    } else if (canRenderEbook) {
      body = (
        <WebView
          ref={webRef}
          originWhitelist={["*"]}
          source={{ uri: ebookFileUri as string }}
          style={{ flex: 1, backgroundColor: colors.surface }}
          onMessage={onWebMessage}
          javaScriptEnabled
          domStorageEnabled
          allowFileAccess
          allowUniversalAccessFromFileURLs
          mixedContentMode="always"
        />
      );
    } else if (ebookStatus === "toobig") {
      body = <Fallback message="This ebook is too large to display in-app — open it in a dedicated reader app for the best experience." />;
    } else {
      body = (
        <Fallback
          message={`Couldn't open this ${formatLabel} in-app. Check your connection and try again, or open it in another app.${ebookError ? `\n\n${ebookError}` : ""}`}
          onRetry={() => { setEbookError(""); setReloadKey((k) => k + 1); }}
        />
      );
    }
  } else if (isPdf && pdfError) {
    // A PDF LOAD failure is not a format problem — the old fallthrough told
    // the user the format was unsupported and offered no way back.
    body = (
      <Fallback
        message="Couldn't open this PDF. Check your connection and try again, or open it in another app."
        onRetry={() => setPdfError(false)}
      />
    );
  } else if (isShareOnly) {
    body = (
      <Fallback
        message={`${format ? format.toUpperCase() + " ebooks" : "This format"} can't be displayed in-app. Open it in a reader app that supports it.`}
      />
    );
  } else {
    body = <Fallback message="This ebook format can't be viewed in-app yet." />;
  }

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.surface }} edges={["top", "left", "right"]}>
      {Header}
      <View style={{ flex: 1 }}>{body}</View>

      {/* PDF footer — page indicator + focusable prev/next (a11y: PDF page
          turns are otherwise scroll-only, unreachable under TalkBack), mirroring
          the epub footer's buttons below. */}
      {canRenderPdf && pdfProgress && (
        <View
          style={{
            flexDirection: "row",
            alignItems: "center",
            paddingVertical: 6,
            paddingHorizontal: 12,
            backgroundColor: colors.surface,
            borderTopWidth: 1,
            borderTopColor: colors.outlineVariant,
          }}
        >
          <Pressable
            onPress={() => setPdfPage((p) => Math.max(1, p - 1))}
            disabled={pdfProgress.page <= 1}
            accessibilityRole="button"
            accessibilityLabel="Previous page"
            accessibilityState={{ disabled: pdfProgress.page <= 1 }}
            hitSlop={8}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", opacity: pdfProgress.page <= 1 ? 0.4 : 1 }}
          >
            <Icon name="chevron-left" size={22} color={colors.onSurfaceVariant} />
          </Pressable>
          <Text style={{ flex: 1, textAlign: "center", color: colors.onSurfaceVariant, fontSize: 12 }}>
            Page {pdfProgress.page} of {pdfProgress.pages}
          </Text>
          <Pressable
            onPress={() => setPdfPage((p) => Math.min(pdfProgress.pages || p + 1, p + 1))}
            disabled={pdfProgress.page >= pdfProgress.pages}
            accessibilityRole="button"
            accessibilityLabel="Next page"
            accessibilityState={{ disabled: pdfProgress.page >= pdfProgress.pages }}
            hitSlop={8}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", opacity: pdfProgress.page >= pdfProgress.pages ? 0.4 : 1 }}
          >
            <Icon name="chevron-right" size={22} color={colors.onSurfaceVariant} />
          </Pressable>
        </View>
      )}

      {/* Footer Progress Indicators */}
      {isFoliateFormat && canRenderEbook && pageProgress && (
        <View
          style={{
            flexDirection: "row",
            alignItems: "center",
            paddingVertical: 6,
            paddingHorizontal: 12,
            backgroundColor: colors.surface,
            borderTopWidth: 1,
            borderTopColor: colors.outlineVariant,
          }}
        >
          {/* Page turning is otherwise gesture-only inside the WebView (tap
              zones/swipes on document listeners) — with TalkBack running
              there is no focusable way to turn a page without these. */}
          <Pressable
            onPress={() => webRef.current?.injectJavaScript("window.goPrev && window.goPrev();true;")}
            accessibilityRole="button"
            accessibilityLabel="Previous page"
            hitSlop={8}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
          >
            <Icon name="chevron-left" size={22} color={colors.onSurfaceVariant} />
          </Pressable>
          <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
            {pageProgress.tocItem?.label ? (
              <Text numberOfLines={1} style={{ color: colors.onSurfaceVariant, fontSize: 13, fontWeight: "600", marginBottom: 2 }}>
                {pageProgress.tocItem.label}
              </Text>
            ) : null}
            <Text style={{ color: colors.onSurfaceVariant, fontSize: 12 }}>
              {/* Percent clamped to 1–99 while mid-book: never "0%" right after
                  starting, and "100%" only at the finished threshold (>=0.99,
                  matching the isFinished sync cutoff). */}
              Page {pageProgress.page} of {pageProgress.pages} (
              {pageProgress.fraction >= 0.99
                ? 100
                : Math.max(pageProgress.fraction > 0 ? 1 : 0, Math.min(99, Math.round(pageProgress.fraction * 100)))}
              %)
            </Text>
          </View>
          <Pressable
            onPress={() => webRef.current?.injectJavaScript("window.goNext && window.goNext();true;")}
            accessibilityRole="button"
            accessibilityLabel="Next page"
            hitSlop={8}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
          >
            <Icon name="chevron-right" size={22} color={colors.onSurfaceVariant} />
          </Pressable>
        </View>
      )}

      {/* Spacer to clear bottom miniplayer or safe navigation bar */}
      <View style={{ height: bottomReserve, backgroundColor: colors.surface }} />

      {/* Table of Contents Slide-up Modal */}
      <BottomSheet visible={showToc} onClose={() => setShowToc(false)} showHandle={false}>
        <View style={{ paddingBottom: 16 }}>
            {/* Modal Header */}
            <View
              style={{
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "space-between",
                padding: 16,
                borderBottomWidth: 1,
                borderBottomColor: colors.outlineVariant,
              }}
            >
              <Text style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700" }}>Table of Contents</Text>
              <Pressable
                onPress={() => setShowToc(false)}
                hitSlop={8}
                style={{ width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }}
                accessibilityRole="button"
                accessibilityLabel="Close table of contents"
              >
                <Icon name="close" size={24} color={colors.onSurface} />
              </Pressable>
            </View>

            {/* List */}
            {toc.length > 0 ? (
              <FlatList
                data={toc}
                renderItem={renderTocItem}
                keyExtractor={(_, index) => String(index)}
                contentContainerStyle={{ paddingVertical: 8 }}
              />
            ) : (
              <View style={{ padding: 48, alignItems: "center" }}>
                <Text style={{ color: colors.onSurfaceVariant, fontSize: 15 }}>No table of contents available.</Text>
              </View>
            )}
        </View>
      </BottomSheet>

      {/* Text Settings Slide-up Modal */}
      <BottomSheet visible={showSettings} onClose={() => setShowSettings(false)} showHandle={false}>
        <View style={{ padding: 20, paddingBottom: 20 }}>
            {/* Modal Header */}
            <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
              <Text style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700" }}>Reading Settings</Text>
              <Pressable
                onPress={() => setShowSettings(false)}
                hitSlop={8}
                style={{ width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }}
                accessibilityRole="button"
                accessibilityLabel="Close reading settings"
              >
                <Icon name="close" size={24} color={colors.onSurface} />
              </Pressable>
            </View>

            {/* Text Size Control */}
            <View style={{ marginBottom: 24 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Text Size</Text>
              <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}>
                <Pressable
                  onPress={() => setFontSize(prev => Math.max(FONT_SIZE_MIN, prev - 10))}
                  disabled={fontSize <= FONT_SIZE_MIN}
                  accessibilityRole="button"
                  accessibilityLabel="Decrease text size"
                  accessibilityState={{ disabled: fontSize <= FONT_SIZE_MIN }}
                  style={{
                    width: 48, height: 48, borderRadius: 24, backgroundColor: colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                    opacity: fontSize <= FONT_SIZE_MIN ? 0.4 : 1,
                  }}
                >
                  <Text style={{ color: colors.onSecondaryContainer, fontSize: 20, fontWeight: "700" }}>-</Text>
                </Pressable>
                {/* Live region: each +/- step announces the new value. */}
                <Text
                  accessibilityLiveRegion="polite"
                  style={{ color: colors.onSurface, fontSize: 16, fontWeight: "600" }}
                >
                  {fontSize}%
                </Text>
                <Pressable
                  onPress={() => setFontSize(prev => Math.min(FONT_SIZE_MAX, prev + 10))}
                  disabled={fontSize >= FONT_SIZE_MAX}
                  accessibilityRole="button"
                  accessibilityLabel="Increase text size"
                  accessibilityState={{ disabled: fontSize >= FONT_SIZE_MAX }}
                  style={{
                    width: 48, height: 48, borderRadius: 24, backgroundColor: colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                    opacity: fontSize >= FONT_SIZE_MAX ? 0.4 : 1,
                  }}
                >
                  <Text style={{ color: colors.onSecondaryContainer, fontSize: 20, fontWeight: "700" }}>+</Text>
                </Pressable>
              </View>
            </View>

            {/* Font Family Control */}
            <View style={{ marginBottom: 24 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Font Family</Text>
              <View style={{ flexDirection: "row", columnGap: 12 }}>
                <Pressable
                  onPress={() => setFontFamily("serif")}
                  accessibilityRole="button"
                  accessibilityState={{ selected: fontFamily === "serif" }}
                  style={{
                    flex: 1, height: 48, borderRadius: 12,
                    backgroundColor: fontFamily === "serif" ? colors.primary : colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                  }}
                >
                  <Text style={{ color: fontFamily === "serif" ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>Serif</Text>
                </Pressable>
                <Pressable
                  onPress={() => setFontFamily("sans-serif")}
                  accessibilityRole="button"
                  accessibilityState={{ selected: fontFamily === "sans-serif" }}
                  style={{
                    flex: 1, height: 48, borderRadius: 12,
                    backgroundColor: fontFamily === "sans-serif" ? colors.primary : colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                  }}
                >
                  <Text style={{ color: fontFamily === "sans-serif" ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>Sans-Serif</Text>
                </Pressable>
              </View>
            </View>

            {/* Line Spacing Control */}
            <View style={{ marginBottom: 12 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Line Spacing</Text>
              <View style={{ flexDirection: "row", columnGap: 12 }}>
                {[
                  { label: "Narrow", val: 1.2 },
                  { label: "Medium", val: 1.5 },
                  { label: "Wide", val: 1.8 },
                ].map(item => (
                  <Pressable
                    key={item.label}
                    onPress={() => setLineHeight(item.val)}
                    accessibilityRole="button"
                    accessibilityLabel={`${item.label} line spacing`}
                    accessibilityState={{ selected: lineHeight === item.val }}
                    style={{
                      flex: 1, height: 48, borderRadius: 12,
                      backgroundColor: lineHeight === item.val ? colors.primary : colors.secondaryContainer,
                      alignItems: "center", justifyContent: "center",
                    }}
                  >
                    <Text style={{ color: lineHeight === item.val ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>{item.label}</Text>
                  </Pressable>
                ))}
              </View>
            </View>

            {/* Page-turn animation (finger-follow curl) */}
            <View style={{ marginTop: 12, marginBottom: 12 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Page Turn</Text>
              <View style={{ flexDirection: "row", columnGap: 12 }}>
                {[
                  { label: "Curl", val: true },
                  { label: "None", val: false },
                ].map(item => (
                  <Pressable
                    key={item.label}
                    onPress={() => setPageCurl(item.val)}
                    accessibilityRole="button"
                    accessibilityLabel={item.val ? "Page-turn curl animation" : "No page-turn animation"}
                    accessibilityState={{ selected: pageCurl === item.val }}
                    style={{
                      flex: 1, height: 48, borderRadius: 12,
                      backgroundColor: pageCurl === item.val ? colors.primary : colors.secondaryContainer,
                      alignItems: "center", justifyContent: "center",
                    }}
                  >
                    <Text style={{ color: pageCurl === item.val ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>{item.label}</Text>
                  </Pressable>
                ))}
              </View>
            </View>
        </View>
      </BottomSheet>
    </SafeAreaView>
  );
}
