import React, { useState, useEffect, useRef, useCallback } from "react";
import { View, Text, Linking, ActivityIndicator, FlatList, Animated, Alert } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import * as FileSystem from "expo-file-system/legacy";
import { useKeepAwake } from "expo-keep-awake";
import { storageHelper, storage } from "../utils/storage";
import { useThemeColors } from "../theme/useThemeColors";
import { usePlaybackStore } from "../store/usePlaybackStore";
import Icon from "../components/Icon";
import { api } from "../utils/api";
import { queueEbookProgressPatch } from "../utils/progressSync";
import { useUserStore } from "../store/useUserStore";
import { useDownloadStore } from "../store/useDownloadStore";
import { FOLIATE_BUNDLE } from "../utils/foliateBundle";
import BottomSheet from "../components/BottomSheet";
import Pressable from "../components/HintPressable";

// Height of the collapsed mini player (mirrors PlayerBottomSheet MINIPLAYER_HEIGHT)
// so reader content can reserve space and not sit underneath it.
const MINIPLAYER_HEIGHT = 68;

// Defensive native-module imports so a build without them can't crash the app.
let Pdf: any = null;
try { Pdf = require("react-native-pdf").default; } catch (e) { Pdf = null; }
let WebView: any = null;
try { WebView = require("react-native-webview").WebView; } catch (e) { WebView = null; }
let Sharing: any = null;
try { Sharing = require("expo-sharing"); } catch (e) { Sharing = null; }

// Cap for inlining the ebook as base64 into the WebView. Most ebooks are 1–5MB;
// beyond this the bridge transfer gets heavy, so we offer "open externally".
const MAX_EBOOK_INLINE_BYTES = 12 * 1024 * 1024;

// Text-size stepper bounds (percent of the publisher's base size).
const FONT_SIZE_MIN = 80;
const FONT_SIZE_MAX = 180;

// foliate-js is VENDORED (utils/foliateBundle.ts, generated by
// scripts/build-foliate-bundle.mjs) and inlined into the reader HTML below, so
// the ebook reader renders fully OFFLINE — no jsdelivr CDN at read time.

// Builds the foliate-js reader HTML. The book bytes are passed in as base64
// so no CORS/auth request happens in the WebView. Themed to the app surface,
// paginated, with swipe + tap-to-turn gestures and animated page transitions;
// progress is reported back to RN via postMessage.
function ebookHtml(
  base64: string,
  bg: string,
  fg: string,
  accent: string,
  startCfi: string,
  mimeHint: string,
  fontSize: number,
  fontFamily: string,
  lineHeight: number
): string {
  // Compute the filename extension for foliate-js format detection
  const ext = mimeHint === "application/epub+zip" ? ".epub" : mimeHint === "application/x-mobipocket-ebook" ? ".mobi" : ".azw3";
  return `<!DOCTYPE html><html><head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<style>
  html,body{margin:0;padding:0;height:100%;background:${bg};overflow:hidden;}
  foliate-view{height:100%;width:100%;}
  #msg{position:absolute;top:0;left:0;right:0;bottom:0;display:flex;align-items:center;justify-content:center;
    color:${fg};font-family:sans-serif;padding:24px;text-align:center;z-index:10;}
</style>
<style id="reader-margins">
  foliate-view::part(head) {
    height: 16px !important;
    min-height: 16px !important;
  }
  foliate-view::part(foot) {
    height: 16px !important;
    min-height: 16px !important;
  }
</style>
</head><body>
<div id="msg">Loading…</div>
<script>
  // Polyfills for foliate-js on OLDER Android System WebViews. foliate-js
  // uses Object.groupBy / Map.groupBy (Chrome 117+, late 2023); many devices
  // run an older, non-auto-updating System WebView, where the reader would
  // otherwise fail with "Object.groupBy is not a function". Must run BEFORE
  // the foliate module below (classic script executes first).
  (function(){
    function groupByInto(make, get, set, items, cb){
      var res = make(), i = 0;
      for (var it of items){ var k = cb(it, i++); var a = get(res, k); if (a) a.push(it); else set(res, k, [it]); }
      return res;
    }
    if (typeof Object.groupBy !== 'function') {
      Object.groupBy = function(items, cb){
        return groupByInto(function(){return Object.create(null);},
          function(o,k){return o[k];}, function(o,k,v){o[k]=v;}, items, cb);
      };
    }
    if (typeof Map.groupBy !== 'function') {
      Map.groupBy = function(items, cb){
        return groupByInto(function(){return new Map();},
          function(m,k){return m.get(k);}, function(m,k,v){m.set(k,v);}, items, cb);
      };
    }
  })();
</script>
<script type="module">
  // Vendored foliate-js, inlined (no network). Registers the <foliate-view>
  // custom element as a side effect; inline module scripts avoid the file://
  // CORS wall that blocks external module imports in Android WebView.
${FOLIATE_BUNDLE}

  const bg = "${bg}";
  const fg = "${fg}";
  const accent = "${accent}";

  function post(o){ try{ window.ReactNativeWebView.postMessage(JSON.stringify(o)); }catch(e){} }

  // Decode base64 to a File/Blob for foliate-js
  function base64ToFile(b64, name) {
    var bin = atob(b64);
    var len = bin.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
    return new File([bytes], name, { type: "${mimeHint}" });
  }

  async function init() {
    try {
      while (window.innerWidth === 0 || window.innerHeight === 0) {
        await new Promise(resolve => setTimeout(resolve, 50));
      }
      var file = base64ToFile("${base64}", "book${ext}");
      var view = document.createElement('foliate-view');
      view.setAttribute('margin', '16px');
      document.body.append(view);

      // Apply reading styles — theme colors and typography
      var fontValue = "${fontFamily}" === "serif" ? "Georgia, serif" : "system-ui, sans-serif";
      var readerCSS = \`
        @namespace epub "http://www.idpf.org/2007/ops";
        html { color-scheme: light dark; }
        body {
          background: \${bg} !important;
          color: \${fg} !important;
          font-size: ${fontSize}% !important;
          text-align: start;
          -webkit-hyphens: auto;
          hyphens: auto;
        }
        body, p, li, blockquote, dd, div, span, a {
          font-family: \${fontValue} !important;
          line-height: ${lineHeight} !important;
        }
        pre { white-space: pre-wrap !important; }
      \`;
      view.addEventListener('load', e => {
        e.detail?.doc?.documentElement?.setAttribute?.('style',
          'background:' + bg + ' !important; color:' + fg + ' !important;');
      });

      // Track relocations — report progress back to React Native
      view.addEventListener('relocate', e => {
        var detail = e.detail;
        if (detail) {
          post({
            type: 'location',
            cfi: detail.cfi || '',
            fraction: detail.fraction || 0,
            section: detail.section || 0,
            page: (view.renderer.page || 0) + 1,
            pages: view.renderer.pages || 1,
            tocItem: detail.tocItem ? { label: detail.tocItem.label || '' } : null,
          });
        }
      });

      await view.open(file);
      document.getElementById('msg').style.display = 'none';

      // Send TOC back to React Native
      post({
        type: 'toc',
        toc: view.book.toc || []
      });

      // Apply styles after opening
      view.renderer.setStyles?.(readerCSS);

      // Restore saved position. JSON.stringify escapes the CFI — a stored or
      // server value containing a quote/backslash/newline would otherwise
      // break (or inject into) this generated script.
      var startCfi = ${startCfi ? JSON.stringify(String(startCfi)) : "null"};
      if (startCfi) {
        try { await view.goTo(startCfi); } catch(e) {}
      } else {
        try { await view.goTo(0); } catch(e) {}
      }

      // Expose navigation functions for RN injection and gesture handling
      window.goNext = () => { try { view.goRight(); } catch(e) {} };
      window.goPrev = () => { try { view.goLeft(); } catch(e) {} };
      window.goToHref = (href) => { try { view.goTo(href); } catch(e) {} };
      // Fraction navigation for the player's "Read from here" jump (percent
      // format switching) — called from RN via injectJavaScript after 'ready'.
      window.goToFraction = (f) => { try { view.goToFraction(f); } catch(e) {} };
      window.setReaderStyles = (css) => { try { view.renderer.setStyles(css); } catch(e) {} };

      // Touch gestures on the outer container — swipe and tap zones
      var sx = 0, sy = 0, st = 0;
      document.addEventListener('touchstart', function(e) {
        var t = e.changedTouches[0]; sx = t.clientX; sy = t.clientY; st = Date.now();
      }, { passive: true });
      document.addEventListener('touchend', function(e) {
        var t = e.changedTouches[0];
        var dx = t.clientX - sx, dy = t.clientY - sy, dt = Date.now() - st;
        var w = window.innerWidth || 360;
        if (Math.abs(dx) < 10 && Math.abs(dy) < 10 && dt < 300) {
          if (t.clientX < w * 0.3) window.goPrev();
          else if (t.clientX > w * 0.7) window.goNext();
        } else if (Math.abs(dx) > 40 && Math.abs(dx) > Math.abs(dy) * 1.2 && dt < 700) {
          if (dx < 0) window.goNext(); else window.goPrev();
        }
      }, { passive: true });

      // Keyboard navigation
      document.addEventListener('keyup', function(e) {
        if (e.key === 'ArrowRight') window.goNext();
        else if (e.key === 'ArrowLeft') window.goPrev();
      });

      post({ type: 'ready' });
    } catch (e) {
      document.getElementById('msg').innerText = 'Could not open this ebook: ' + e.message;
      post({ type: 'error', message: String(e) });
    }
  }
  init();
</script>
</body></html>`;
}

// Map file extensions to MIME types for foliate-js File constructor
function getMimeForFormat(format: string): string {
  switch (format) {
    case "epub": return "application/epub+zip";
    case "mobi": return "application/x-mobipocket-ebook";
    case "azw3": case "azw": case "kf8": return "application/x-mobipocket-ebook";
    default: return "application/octet-stream";
  }
}

// Map file extensions to expected filename suffixes for foliate-js format detection
function getExtForFormat(format: string): string {
  switch (format) {
    case "epub": return ".epub";
    case "mobi": return ".mobi";
    case "azw3": case "kf8": return ".azw3";
    case "azw": return ".azw";
    default: return "." + format;
  }
}

export default function ReaderScreen({ route, navigation }: any) {
  const colors = useThemeColors();
  const insets = useSafeAreaInsets();
  // Reading is a long touch-free activity — keep the screen awake while the
  // reader is mounted (released automatically on unmount).
  useKeepAwake();
  const hasSession = usePlaybackStore((s) => s.currentSession !== null);
  const { itemId, ebookFormat, title } = route.params || {};
  const [pdfError, setPdfError] = useState(false);
  // PDF page tracking: restore the last-read page and show a footer indicator,
  // mirroring what the epub path gets from foliate relocations.
  const pdfPageKey = `pdfPage_${itemId}`;
  const initialPdfPageRef = useRef<number>(Math.max(1, storage.getNumber(`pdfPage_${itemId}`) || 1));
  const [pdfProgress, setPdfProgress] = useState<{ page: number; pages: number } | null>(null);
  // Bumped by the error-state Retry button to re-run the ebook load effect.
  const [reloadKey, setReloadKey] = useState(0);

  // Bottom reserve spacing matches exactly what the floating mini-player consumes.
  // When no session exists, the mini-player slides completely down (height = 0),
  // so we fall back to standard bottom safe inset for spacing.
  const bottomReserve = hasSession ? MINIPLAYER_HEIGHT + insets.bottom : insets.bottom;

  const serverConfig = storageHelper.getServerConfig();
  const serverAddress = serverConfig?.address?.replace(/\/$/, "") || "";
  const token = serverConfig?.token || "";
  const ebookUri = itemId && serverAddress ? `${serverAddress}/api/items/${itemId}/ebook?token=${token}` : "";

  const format = String(ebookFormat || "").replace(/^\./, "").toLowerCase();
  const isPdf = format === "pdf" || (!format && !!ebookUri);
  // foliate-js supports epub, mobi, azw3, azw, kf8
  const isFoliateFormat = ["epub", "mobi", "azw3", "azw", "kf8"].includes(format);
  const isShareOnly = !isPdf && !isFoliateFormat;

  // --- Ebook settings & state (EPUB / MOBI / AZW3) ---
  const [ebookFileUri, setEbookFileUri] = useState<string | null>(null);
  const [ebookStatus, setEbookStatus] = useState<"idle" | "loading" | "ready" | "error" | "toobig">("idle");
  // Why the ebook failed (download vs foliate parse) — shown small on the
  // error screen so a failure is actionable instead of a generic "try again".
  const [ebookError, setEbookError] = useState<string>("");
  const webRef = useRef<any>(null);
  const progressKey = `ebookCfi_${itemId}`;
  const syncTimeoutRef = useRef<any>(null);
  const latestProgressRef = useRef<{ cfi: string; fraction: number } | null>(null);

  // Pulsing animation for loading state
  const pulseAnim = useRef(new Animated.Value(0.6)).current;
  useEffect(() => {
    let anim: Animated.CompositeAnimation | null = null;
    if (ebookStatus === "loading" || ebookStatus === "idle") {
      anim = Animated.loop(
        Animated.sequence([
          Animated.timing(pulseAnim, {
            toValue: 1.0,
            duration: 1000,
            useNativeDriver: true,
          }),
          Animated.timing(pulseAnim, {
            toValue: 0.6,
            duration: 1000,
            useNativeDriver: true,
          }),
        ])
      );
      anim.start();
    } else {
      pulseAnim.setValue(0.6);
    }
    return () => {
      if (anim) anim.stop();
    };
  }, [ebookStatus, pulseAnim]);

  // Style Settings States
  const [fontSize, setFontSize] = useState(() => storage.getNumber("reader_font_size") || 100);
  const [fontFamily, setFontFamily] = useState<"serif" | "sans-serif">(() => (storage.getString("reader_font_family") as any) || "serif");
  const [lineHeight, setLineHeight] = useState(() => storage.getNumber("reader_line_height") || 1.5);

  // TOC and Progress Info States
  const [toc, setToc] = useState<any[]>([]);
  const [showToc, setShowToc] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [pageProgress, setPageProgress] = useState<{
    page: number;
    pages: number;
    fraction: number;
    tocItem: { label: string } | null;
  } | null>(null);

  const bg = colors.surface;
  const fg = colors.onSurface;
  const accent = colors.primary;

  // Dynamically push styles to the reader WebView when text settings change
  useEffect(() => {
    storage.set("reader_font_size", fontSize);
    storage.set("reader_font_family", fontFamily);
    storage.set("reader_line_height", lineHeight);

    if (ebookStatus === "ready" && webRef.current) {
      const fontValue = fontFamily === "serif" ? "Georgia, serif" : "system-ui, sans-serif";
      const css = `
        @namespace epub "http://www.idpf.org/2007/ops";
        html { color-scheme: light dark; }
        body {
          background: ${bg} !important;
          color: ${fg} !important;
          font-size: ${fontSize}% !important;
          text-align: start;
          -webkit-hyphens: auto;
          hyphens: auto;
        }
        body, p, li, blockquote, dd, div, span, a {
          font-family: ${fontValue} !important;
          line-height: ${lineHeight} !important;
        }
        pre { white-space: pre-wrap !important; }
      `;
      // Clean script to inject
      const cleanCSS = css.replace(/`/g, "\\`").replace(/\n/g, "");
      webRef.current.injectJavaScript(`window.setReaderStyles && window.setReaderStyles(\`${cleanCSS}\`);true;`);
    }
  }, [fontSize, fontFamily, lineHeight, ebookStatus, bg, fg, accent]);

  useEffect(() => {
    if (itemId) {
      storage.set(`last_interaction_${itemId}`, "read");
    }
  }, [itemId]);

  // True once the screen is torn down — late WebView messages must not
  // re-arm the sync debounce (the cleanup below already ran).
  const unmountedRef = useRef(false);

  // Sync pending ebook progress to server on unmount/screen change
  useEffect(() => {
    return () => {
      unmountedRef.current = true;
      if (syncTimeoutRef.current) {
        clearTimeout(syncTimeoutRef.current);
      }
      if (latestProgressRef.current) {
        const { cfi, fraction } = latestProgressRef.current;
        console.log("[Reader] Unmounting, flushing ebook progress to server:", itemId, cfi, fraction);
        // ONLY the ebook fields (matches the ABS web reader). Sending
        // `progress`/`isFinished` here would clobber the AUDIO progress on
        // both-format items — e.g. opening the ebook of a book you finished
        // in audio would un-finish it.
        api.patch(`/api/me/progress/${itemId}`, {
          ebookLocation: cfi,
          ebookProgress: fraction,
          // One-way: mark finished when the book is done reading, but never
          // send isFinished:false (that would un-finish audio-finished items).
          ...(fraction >= 0.99 ? { isFinished: true } : {}),
        }).catch((e) => {
          console.warn("[Reader] Failed to sync ebook progress on unmount:", e);
          // Offline (downloaded ebook) — queue so the cfi still reaches the
          // server (and Storyteller/other devices) when connectivity returns.
          queueEbookProgressPatch(itemId, cfi, fraction, fraction >= 0.99);
        });
      }
    };
  }, [itemId]);

  // Load ebook contents and generate the HTML wrapper
  useEffect(() => {
    if (!isFoliateFormat || !WebView || !ebookUri) return;
    setEbookFileUri(null);
    setEbookStatus("loading");
    let cancelled = false;
    (async () => {
      try {
        const localDownload = useDownloadStore.getState().completedDownloads[itemId];
        const ebookPart = localDownload?.parts?.find(p => p.id === "ebook");
        
        let fileUri = "";
        if (ebookPart?.localFilePath) {
          fileUri = ebookPart.localFilePath;
          console.log("[Reader] Loading ebook from offline download:", fileUri);
        } else {
          const ext = getExtForFormat(format);
          const localPath = `${FileSystem.cacheDirectory}reader_${itemId}${ext}`;
          const dl = await FileSystem.downloadAsync(ebookUri, localPath, {
            headers: { Authorization: `Bearer ${token}` },
          });
          fileUri = dl.uri;
        }

        const info = await FileSystem.getInfoAsync(fileUri);
        if ((info as any).size && (info as any).size > MAX_EBOOK_INLINE_BYTES) {
          if (!ebookPart?.localFilePath) {
            FileSystem.deleteAsync(fileUri, { idempotent: true }).catch(() => {});
          }
          if (!cancelled) setEbookStatus("toobig");
          return;
        }
        const base64 = await FileSystem.readAsStringAsync(fileUri, {
          encoding: FileSystem.EncodingType.Base64,
        });
        if (!ebookPart?.localFilePath) {
          FileSystem.deleteAsync(fileUri, { idempotent: true }).catch(() => {});
        }
        if (cancelled) return;
        // Restore position: local (MMKV) vs server ebookLocation — prefer the
        // FRESHER one, so reading ahead on another device isn't lost to a stale
        // local cfi. The local save timestamp is written alongside every cfi in
        // onWebMessage; the server side uses the progress entry's lastUpdate.
        // Caveat (accepted): lastUpdate also bumps on audio-only syncs, but the
        // reader mirrors every cfi to the server too, so when nobody else read
        // further the two cfis match and the choice is moot.
        const localCfi = storage.getString(progressKey) || "";
        const localCfiAt = storage.getNumber(`${progressKey}_at`) || 0;
        const serverProgress = useUserStore.getState().mediaProgress[itemId];
        const serverCfi = serverProgress?.ebookLocation || "";
        const serverCfiAt = Number(serverProgress?.lastUpdate || serverProgress?.updatedAt || 0);
        const savedCfi =
          serverCfi && serverCfi !== localCfi && serverCfiAt > localCfiAt
            ? serverCfi
            : localCfi || serverCfi;

        const mime = getMimeForFormat(format);
        const htmlContent = ebookHtml(base64, bg, fg, accent, savedCfi, mime, fontSize, fontFamily, lineHeight);
        const htmlPath = `${FileSystem.cacheDirectory}reader_${itemId}.html`;
        await FileSystem.writeAsStringAsync(htmlPath, htmlContent, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        if (cancelled) return;
        setEbookFileUri(htmlPath);
        setEbookStatus("ready");
      } catch (e: any) {
        console.warn("[Reader] ebook load failed", e);
        if (!cancelled) {
          setEbookError(`load: ${e?.message || String(e)}`);
          setEbookStatus("error");
        }
      }
    })();
    return () => { cancelled = true; };
  }, [isFoliateFormat, ebookUri, reloadKey]);

  const onWebMessage = useCallback((event: any) => {
    try {
      if (unmountedRef.current) return;
      const data = JSON.parse(event.nativeEvent.data);
      if (data.type === "location") {
        // Sanitize at the trust boundary: foliate/webview payloads can carry
        // out-of-range fractions (a fraction of 2 would ONE-WAY auto-finish
        // the book server-side) and non-string cfis (unrecoverable MMKV
        // writes).
        const rawFraction = Number(data.fraction);
        data.fraction = Number.isFinite(rawFraction) ? Math.min(1, Math.max(0, rawFraction)) : 0;
        if (typeof data.cfi !== "string") data.cfi = "";
        if (data.cfi) {
          storage.set(progressKey, data.cfi);
          // Save-time timestamp so the restore logic can compare local vs
          // server freshness (see the load effect above).
          storage.set(`${progressKey}_at`, Date.now());
          latestProgressRef.current = { cfi: data.cfi, fraction: data.fraction || 0 };
        }
        setPageProgress({
          page: data.page || 1,
          pages: data.pages || 1,
          fraction: data.fraction || 0,
          tocItem: data.tocItem || null,
        });

        // Update local store progress state instantly — EBOOK fields only.
        // Touching `progress`/`isFinished` here would clobber the audio
        // progress on both-format items (and un-finish finished audiobooks).
        const updatedProgress = {
          libraryItemId: itemId,
          ebookLocation: data.cfi || "",
          ebookProgress: data.fraction || 0,
          updatedAt: Date.now(),
        };
        useUserStore.setState({
          mediaProgress: {
            ...useUserStore.getState().mediaProgress,
            [itemId]: {
              ...useUserStore.getState().mediaProgress[itemId],
              ...updatedProgress,
            },
          },
        });

        // Debounce progress PATCH to server (ebook fields only, matching the
        // ABS web reader).
        if (syncTimeoutRef.current) {
          clearTimeout(syncTimeoutRef.current);
        }
        syncTimeoutRef.current = setTimeout(async () => {
          try {
            await api.patch(`/api/me/progress/${itemId}`, {
              ebookLocation: data.cfi || "",
              ebookProgress: data.fraction || 0,
              ...((data.fraction || 0) >= 0.99 ? { isFinished: true } : {}),
            });
          } catch (e) {
            console.warn("[Reader] Failed to sync ebook progress:", e);
            // Offline — queue (ebook fields only) instead of dropping it.
            queueEbookProgressPatch(
              itemId,
              data.cfi || "",
              data.fraction || 0,
              (data.fraction || 0) >= 0.99
            );
          }
        }, 2000);
      } else if (data.type === "toc") {
        setToc(data.toc || []);
      } else if (data.type === "error") {
        setEbookError(`render: ${data.message || "unknown"}`);
        setEbookStatus("error");
      }
    } catch {}
  }, [progressKey, itemId]);

  const openExternally = async () => {
    try {
      if (Sharing && (await Sharing.isAvailableAsync())) {
        const localPath = `${FileSystem.cacheDirectory}book_${itemId}.${format || "bin"}`;
        const dl = await FileSystem.downloadAsync(ebookUri, localPath, {
          headers: { Authorization: `Bearer ${token}` },
        });
        await Sharing.shareAsync(dl.uri, { dialogTitle: title || "Open ebook" });
        return;
      }
    } catch (e) {
      console.warn("[Reader] share failed", e);
    }
    if (ebookUri) Linking.openURL(ebookUri).catch(() => {});
  };

  const selectTocItem = (href: string) => {
    // href comes from the EBOOK's own TOC via the bridge — untrusted. Escape
    // like startCfi (JSON.stringify): raw interpolation both broke navigation
    // for titles with quotes AND let a crafted epub execute arbitrary JS in
    // the reader WebView, which holds the native bridge.
    if (typeof href !== "string" || !href) return;
    if (webRef.current) {
      webRef.current.injectJavaScript(
        `window.goToHref && window.goToHref(${JSON.stringify(String(href))});true;`
      );
      setShowToc(false);
    }
  };

  const canRenderPdf = Pdf !== null && isPdf && !pdfError && !!ebookUri;
  const canRenderEbook = WebView !== null && isFoliateFormat && ebookStatus === "ready" && !!ebookFileUri;

  const formatLabel = format ? format.toUpperCase() : "ebook";

  const Header = (
    <View style={{ flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingTop: 8, paddingBottom: 8 }}>
      <Pressable
        onPress={() => navigation.goBack()}
        style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
        hitSlop={8}
        accessibilityRole="button"
        accessibilityLabel="Close reader"
      >
        <Icon name="back" size={24} color={colors.onSurface} />
      </Pressable>
      <Text numberOfLines={1} style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700", marginLeft: 4, flex: 1 }}>
        {title || "Reader"}
      </Text>
      {isFoliateFormat && canRenderEbook ? (
        <View style={{ flexDirection: "row", alignItems: "center", columnGap: 4 }}>
          <Pressable
            onPress={() => setShowToc(true)}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
            hitSlop={8}
            accessibilityRole="button"
            accessibilityLabel="Table of contents"
          >
            <Icon name="list" size={24} color={colors.onSurface} />
          </Pressable>
          <Pressable
            onPress={() => setShowSettings(true)}
            style={{ width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }}
            hitSlop={8}
            accessibilityRole="button"
            accessibilityLabel="Reading settings"
          >
            <Icon name="settings" size={24} color={colors.onSurface} />
          </Pressable>
        </View>
      ) : null}
    </View>
  );

  const Fallback = ({
    message,
    showShare = true,
    onRetry,
  }: {
    message: string;
    showShare?: boolean;
    onRetry?: () => void;
  }) => (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 32 }}>
      <View
        style={{
          width: 72, height: 72, borderRadius: 36, backgroundColor: colors.secondaryContainer,
          alignItems: "center", justifyContent: "center", marginBottom: 16,
        }}
      >
        <Icon name="book" size={36} color={colors.onSecondaryContainer} />
      </View>
      <Text style={{ color: colors.onSurface, fontSize: 15, textAlign: "center", marginBottom: 20 }}>
        {message}
      </Text>
      {onRetry ? (
        <Pressable
          onPress={onRetry}
          accessibilityRole="button"
          style={{
            backgroundColor: colors.primary, paddingHorizontal: 24, height: 48, borderRadius: 24,
            alignItems: "center", justifyContent: "center", flexDirection: "row", marginBottom: 12,
          }}
        >
          <Icon name="refresh" size={20} color={colors.onPrimary} />
          <Text style={{ color: colors.onPrimary, fontSize: 15, fontWeight: "600", marginLeft: 8 }}>
            Try again
          </Text>
        </Pressable>
      ) : null}
      {showShare ? (
        <Pressable
          onPress={openExternally}
          accessibilityRole="button"
          style={{
            // Secondary action when Retry is present, primary otherwise.
            backgroundColor: onRetry ? colors.secondaryContainer : colors.primary,
            paddingHorizontal: 24, height: 48, borderRadius: 24,
            alignItems: "center", justifyContent: "center", flexDirection: "row",
          }}
        >
          <Icon name="share" size={20} color={onRetry ? colors.onSecondaryContainer : colors.onPrimary} />
          <Text
            style={{
              color: onRetry ? colors.onSecondaryContainer : colors.onPrimary,
              fontSize: 15, fontWeight: "600", marginLeft: 8,
            }}
          >
            Open in another app
          </Text>
        </Pressable>
      ) : null}
    </View>
  );

  // Recursive rendering helper for TOC hierarchical lists (subitems).
  // The section currently being read (foliate reports it on every relocate)
  // is tinted primary so long TOCs are scannable for "where am I".
  const currentTocLabel = pageProgress?.tocItem?.label || null;
  const renderTocItem = ({ item }: { item: any }) => {
    // Trust boundary: a malformed TOC (object label, string subitems) came
    // straight from the WebView and hard-crashed this renderer.
    const label = typeof item?.label === "string" && item.label ? item.label : "Untitled Section";
    const subitems = Array.isArray(item?.subitems) ? item.subitems : [];
    const isCurrent = !!currentTocLabel && label === currentTocLabel;
    return (
      <View style={{ marginLeft: 8 }}>
        <Pressable
          onPress={() => selectTocItem(item.href)}
          accessibilityRole="button"
          accessibilityLabel={label}
          accessibilityState={{ selected: isCurrent }}
          style={{
            paddingVertical: 14,
            paddingHorizontal: 16,
            borderBottomWidth: 1,
            borderBottomColor: colors.outlineVariant,
            flexDirection: "row",
            alignItems: "center",
          }}
        >
          <Text
            style={{
              flex: 1,
              color: isCurrent ? colors.primary : colors.onSurface,
              fontSize: 16,
              fontWeight: isCurrent ? "700" : "500",
            }}
          >
            {label}
          </Text>
          {isCurrent ? <Icon name="bookmark" size={18} color={colors.primary} /> : null}
        </Pressable>
        {subitems.length > 0 && (
          <View style={{ paddingLeft: 12, borderLeftWidth: 1, borderLeftColor: colors.outlineVariant }}>
            {subitems.map((sub: any, idx: number) => (
              <View key={idx}>
                {renderTocItem({ item: sub })}
              </View>
            ))}
          </View>
        )}
      </View>
    );
  };

  let body: React.ReactNode;
  if (canRenderPdf) {
    // Prefer the downloaded PDF file — the remote URL is dead exactly when
    // downloads matter (offline), which previously dead-ended a downloaded
    // PDF at the generic "can't be viewed" fallback.
    const localPdf = useDownloadStore
      .getState()
      .completedDownloads[itemId]?.parts?.find((p: any) => p.id === "ebook")?.localFilePath;
    body = (
      <Pdf
        source={
          localPdf
            ? { uri: localPdf }
            : { uri: ebookUri, headers: { Authorization: `Bearer ${token}` } }
        }
        style={{ flex: 1, backgroundColor: colors.surface }}
        page={initialPdfPageRef.current}
        onPageChanged={(page: number, numberOfPages: number) => {
          setPdfProgress({ page, pages: numberOfPages });
          // Remember where the user left off so reopening resumes here.
          storage.set(pdfPageKey, page);
        }}
        onError={() => setPdfError(true)}
      />
    );
  } else if (isFoliateFormat) {
    if (!WebView) {
      // Native WebView module missing from this build — without this branch
      // the screen would sit on the loading state forever.
      body = <Fallback message="The in-app reader isn't available in this build. Open the ebook in another app instead." />;
    } else if (ebookStatus === "loading" || ebookStatus === "idle") {
      body = (
        <View style={{ flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }}>
          <Animated.View style={{ opacity: pulseAnim, transform: [{ scale: pulseAnim }], marginBottom: 20 }}>
            <View style={{
              width: 72, height: 72, borderRadius: 36, backgroundColor: colors.secondaryContainer,
              alignItems: "center", justifyContent: "center"
            }}>
              <Icon name="book" size={36} color={colors.primary} />
            </View>
          </Animated.View>
          <ActivityIndicator size="small" color={colors.primary} />
          <Text style={{ color: colors.onSurface, fontSize: 16, fontWeight: "600", marginTop: 16 }}>
            Preparing your book…
          </Text>
          <Text style={{ color: colors.onSurfaceVariant, fontSize: 12, marginTop: 4 }}>
            Setting up typography and layout
          </Text>
        </View>
      );
    } else if (canRenderEbook) {
      body = (
        <WebView
          ref={webRef}
          originWhitelist={["*"]}
          source={{ uri: ebookFileUri as string }}
          style={{ flex: 1, backgroundColor: colors.surface }}
          onMessage={onWebMessage}
          javaScriptEnabled
          domStorageEnabled
          allowFileAccess
          allowUniversalAccessFromFileURLs
          mixedContentMode="always"
        />
      );
    } else if (ebookStatus === "toobig") {
      body = <Fallback message="This ebook is too large to display in-app — open it in a dedicated reader app for the best experience." />;
    } else {
      body = (
        <Fallback
          message={`Couldn't open this ${formatLabel} in-app. Check your connection and try again, or open it in another app.${ebookError ? `\n\n${ebookError}` : ""}`}
          onRetry={() => { setEbookError(""); setReloadKey((k) => k + 1); }}
        />
      );
    }
  } else if (isShareOnly) {
    body = (
      <Fallback
        message={`${format ? format.toUpperCase() + " ebooks" : "This format"} can't be displayed in-app. Open it in a reader app that supports it.`}
      />
    );
  } else {
    body = <Fallback message="This ebook format can't be viewed in-app yet." />;
  }

  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: colors.surface }} edges={["top", "left", "right"]}>
      {Header}
      <View style={{ flex: 1 }}>{body}</View>

      {/* PDF footer — page indicator matching the epub footer below */}
      {canRenderPdf && pdfProgress && (
        <View
          style={{
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 10,
            paddingHorizontal: 24,
            backgroundColor: colors.surface,
            borderTopWidth: 1,
            borderTopColor: colors.outlineVariant,
          }}
        >
          <Text style={{ color: colors.onSurfaceVariant, fontSize: 12 }}>
            Page {pdfProgress.page} of {pdfProgress.pages}
          </Text>
        </View>
      )}

      {/* Footer Progress Indicators */}
      {isFoliateFormat && canRenderEbook && pageProgress && (
        <View
          style={{
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 10,
            paddingHorizontal: 24,
            backgroundColor: colors.surface,
            borderTopWidth: 1,
            borderTopColor: colors.outlineVariant,
          }}
        >
          {pageProgress.tocItem?.label ? (
            <Text numberOfLines={1} style={{ color: colors.onSurfaceVariant, fontSize: 13, fontWeight: "600", marginBottom: 2 }}>
              {pageProgress.tocItem.label}
            </Text>
          ) : null}
          <Text style={{ color: colors.onSurfaceVariant, fontSize: 12 }}>
            {/* Percent clamped to 1–99 while mid-book: never "0%" right after
                starting, and "100%" only at the finished threshold (>=0.99,
                matching the isFinished sync cutoff). */}
            Page {pageProgress.page} of {pageProgress.pages} (
            {pageProgress.fraction >= 0.99
              ? 100
              : Math.max(pageProgress.fraction > 0 ? 1 : 0, Math.min(99, Math.round(pageProgress.fraction * 100)))}
            %)
          </Text>
        </View>
      )}

      {/* Spacer to clear bottom miniplayer or safe navigation bar */}
      <View style={{ height: bottomReserve, backgroundColor: colors.surface }} />

      {/* Table of Contents Slide-up Modal */}
      <BottomSheet visible={showToc} onClose={() => setShowToc(false)} showHandle={false}>
        <View style={{ paddingBottom: 16 }}>
            {/* Modal Header */}
            <View
              style={{
                flexDirection: "row",
                alignItems: "center",
                justifyContent: "space-between",
                padding: 16,
                borderBottomWidth: 1,
                borderBottomColor: colors.outlineVariant,
              }}
            >
              <Text style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700" }}>Table of Contents</Text>
              <Pressable
                onPress={() => setShowToc(false)}
                style={{ width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }}
                accessibilityRole="button"
                accessibilityLabel="Close table of contents"
              >
                <Icon name="close" size={24} color={colors.onSurface} />
              </Pressable>
            </View>

            {/* List */}
            {toc.length > 0 ? (
              <FlatList
                data={toc}
                renderItem={renderTocItem}
                keyExtractor={(_, index) => String(index)}
                contentContainerStyle={{ paddingVertical: 8 }}
              />
            ) : (
              <View style={{ padding: 48, alignItems: "center" }}>
                <Text style={{ color: colors.onSurfaceVariant, fontSize: 15 }}>No table of contents available.</Text>
              </View>
            )}
        </View>
      </BottomSheet>

      {/* Text Settings Slide-up Modal */}
      <BottomSheet visible={showSettings} onClose={() => setShowSettings(false)} showHandle={false}>
        <View style={{ padding: 20, paddingBottom: 20 }}>
            {/* Modal Header */}
            <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
              <Text style={{ color: colors.onSurface, fontSize: 18, fontWeight: "700" }}>Reading Settings</Text>
              <Pressable
                onPress={() => setShowSettings(false)}
                style={{ width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }}
                accessibilityRole="button"
                accessibilityLabel="Close reading settings"
              >
                <Icon name="close" size={24} color={colors.onSurface} />
              </Pressable>
            </View>

            {/* Text Size Control */}
            <View style={{ marginBottom: 24 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Text Size</Text>
              <View style={{ flexDirection: "row", alignItems: "center", justifyContent: "space-between" }}>
                <Pressable
                  onPress={() => setFontSize(prev => Math.max(FONT_SIZE_MIN, prev - 10))}
                  disabled={fontSize <= FONT_SIZE_MIN}
                  accessibilityRole="button"
                  accessibilityLabel="Decrease text size"
                  accessibilityState={{ disabled: fontSize <= FONT_SIZE_MIN }}
                  style={{
                    width: 48, height: 48, borderRadius: 24, backgroundColor: colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                    opacity: fontSize <= FONT_SIZE_MIN ? 0.4 : 1,
                  }}
                >
                  <Text style={{ color: colors.onSecondaryContainer, fontSize: 20, fontWeight: "700" }}>-</Text>
                </Pressable>
                <Text style={{ color: colors.onSurface, fontSize: 16, fontWeight: "600" }}>{fontSize}%</Text>
                <Pressable
                  onPress={() => setFontSize(prev => Math.min(FONT_SIZE_MAX, prev + 10))}
                  disabled={fontSize >= FONT_SIZE_MAX}
                  accessibilityRole="button"
                  accessibilityLabel="Increase text size"
                  accessibilityState={{ disabled: fontSize >= FONT_SIZE_MAX }}
                  style={{
                    width: 48, height: 48, borderRadius: 24, backgroundColor: colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                    opacity: fontSize >= FONT_SIZE_MAX ? 0.4 : 1,
                  }}
                >
                  <Text style={{ color: colors.onSecondaryContainer, fontSize: 20, fontWeight: "700" }}>+</Text>
                </Pressable>
              </View>
            </View>

            {/* Font Family Control */}
            <View style={{ marginBottom: 24 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Font Family</Text>
              <View style={{ flexDirection: "row", columnGap: 12 }}>
                <Pressable
                  onPress={() => setFontFamily("serif")}
                  accessibilityRole="button"
                  accessibilityState={{ selected: fontFamily === "serif" }}
                  style={{
                    flex: 1, height: 48, borderRadius: 12,
                    backgroundColor: fontFamily === "serif" ? colors.primary : colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                  }}
                >
                  <Text style={{ color: fontFamily === "serif" ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>Serif</Text>
                </Pressable>
                <Pressable
                  onPress={() => setFontFamily("sans-serif")}
                  accessibilityRole="button"
                  accessibilityState={{ selected: fontFamily === "sans-serif" }}
                  style={{
                    flex: 1, height: 48, borderRadius: 12,
                    backgroundColor: fontFamily === "sans-serif" ? colors.primary : colors.secondaryContainer,
                    alignItems: "center", justifyContent: "center",
                  }}
                >
                  <Text style={{ color: fontFamily === "sans-serif" ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>Sans-Serif</Text>
                </Pressable>
              </View>
            </View>

            {/* Line Spacing Control */}
            <View style={{ marginBottom: 12 }}>
              <Text style={{ color: colors.onSurface, fontSize: 15, fontWeight: "600", marginBottom: 12 }}>Line Spacing</Text>
              <View style={{ flexDirection: "row", columnGap: 12 }}>
                {[
                  { label: "Narrow", val: 1.2 },
                  { label: "Medium", val: 1.5 },
                  { label: "Wide", val: 1.8 },
                ].map(item => (
                  <Pressable
                    key={item.label}
                    onPress={() => setLineHeight(item.val)}
                    accessibilityRole="button"
                    accessibilityLabel={`${item.label} line spacing`}
                    accessibilityState={{ selected: lineHeight === item.val }}
                    style={{
                      flex: 1, height: 48, borderRadius: 12,
                      backgroundColor: lineHeight === item.val ? colors.primary : colors.secondaryContainer,
                      alignItems: "center", justifyContent: "center",
                    }}
                  >
                    <Text style={{ color: lineHeight === item.val ? colors.onPrimary : colors.onSecondaryContainer, fontSize: 15, fontWeight: "600" }}>{item.label}</Text>
                  </Pressable>
                ))}
              </View>
            </View>
        </View>
      </BottomSheet>
    </SafeAreaView>
  );
}
