package com.tomesonic.app;

import android.content.Context;

import com.google.android.gms.cast.framework.CastOptions;
import com.google.android.gms.cast.framework.media.CastMediaOptions;
import com.reactnative.googlecast.GoogleCastOptionsProvider;
import com.reactnative.googlecast.RNGCExpandedControllerActivity;

/**
 * Same options as the library provider, minus NotificationOptions — the cast
 * framework then never posts its duplicate media notification. Generated by
 * plugins/withCastSingleNotification.js.
 */
public class CastOptionsProvider extends GoogleCastOptionsProvider {
  @Override
  public CastOptions getCastOptions(Context context) {
    CastMediaOptions mediaOptions =
        new CastMediaOptions.Builder()
            // No .setNotificationOptions(...) => no cast-framework notification.
            .setNotificationOptions(null)
            .setExpandedControllerActivityClassName(
                RNGCExpandedControllerActivity.class.getName())
            .build();

    return new CastOptions.Builder()
        .setReceiverApplicationId(getReceiverApplicationId(context))
        .setCastMediaOptions(mediaOptions)
        .build();
  }
}
