const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

// The Google Cast framework posts its OWN media notification while casting
// (NotificationOptions built in react-native-google-cast's
// GoogleCastOptionsProvider) — giving the user two notifications for one
// book. We ship a subclass that disables the cast-framework notification
// entirely and point the manifest's OPTIONS_PROVIDER_CLASS_NAME at it; the
// app's normal playback notification stays as the single control surface
// (its transport events already route to the cast client through JS).
const PACKAGE = "com.tomesonic.app";

const PROVIDER_JAVA = `package ${PACKAGE};

import android.content.Context;

import com.google.android.gms.cast.framework.CastOptions;
import com.google.android.gms.cast.framework.media.CastMediaOptions;
import com.reactnative.googlecast.GoogleCastOptionsProvider;
import com.reactnative.googlecast.RNGCExpandedControllerActivity;

/**
 * Same options as the library provider, minus NotificationOptions — the cast
 * framework then never posts its duplicate media notification. Generated by
 * plugins/withCastSingleNotification.js.
 */
public class CastOptionsProvider extends GoogleCastOptionsProvider {
  @Override
  public CastOptions getCastOptions(Context context) {
    CastMediaOptions mediaOptions =
        new CastMediaOptions.Builder()
            // No .setNotificationOptions(...) => no cast-framework notification.
            .setNotificationOptions(null)
            .setExpandedControllerActivityClassName(
                RNGCExpandedControllerActivity.class.getName())
            .build();

    return new CastOptions.Builder()
        .setReceiverApplicationId(getReceiverApplicationId(context))
        .setCastMediaOptions(mediaOptions)
        .build();
  }
}
`;

function withProviderClass(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app/src/main/java",
        ...PACKAGE.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "CastOptionsProvider.java"), PROVIDER_JAVA);

      // The framework instantiates the provider reflectively from manifest
      // meta-data — R8 must keep it or minified builds crash on cast init.
      const proguard = path.join(cfg.modRequest.platformProjectRoot, "app/proguard-rules.pro");
      const KEEP = `-keep class ${PACKAGE}.CastOptionsProvider { *; }`;
      if (fs.existsSync(proguard) && !fs.readFileSync(proguard, "utf8").includes(KEEP)) {
        fs.appendFileSync(
          proguard,
          `\n# Cast framework instantiates the OptionsProvider reflectively from manifest\n# meta-data — keep it or casting crashes on R8 builds (withCastSingleNotification).\n${KEEP}\n`
        );
      }
      return cfg;
    },
  ]);
}

function withProviderMetaData(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application && cfg.modResults.manifest.application[0];
    if (!app) return cfg;
    app["meta-data"] = app["meta-data"] || [];
    const KEY = "com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME";
    // The react-native-google-cast plugin sets this to the library provider;
    // replace it with ours. NOTE: manifest mods run LIFO (later-listed plugin
    // runs FIRST), so this plugin must be listed BEFORE react-native-google-cast
    // in app.json for this replacement to run last and win — verified via
    // `expo config --type introspect`.
    const existing = app["meta-data"].find((m) => m.$ && m.$["android:name"] === KEY);
    if (existing) {
      existing.$["android:value"] = `${PACKAGE}.CastOptionsProvider`;
    } else {
      app["meta-data"].push({
        $: { "android:name": KEY, "android:value": `${PACKAGE}.CastOptionsProvider` },
      });
    }
    return cfg;
  });
}

module.exports = function withCastSingleNotification(config) {
  config = withProviderClass(config);
  config = withProviderMetaData(config);
  return config;
};
