name: Android Tests

on:
  pull_request:
    paths:
      - 'android/**'
      - '.github/workflows/android-tests.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'android/**'
      - '.github/workflows/android-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt project
        run: npm run generate

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Run unit tests
        run: ./android/gradlew test --continue
        working-directory: .

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: google_apis
          arch: x86_64
          script: ./android/gradlew connectedAndroidTest --continue

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            android/app/build/reports/tests/
            android/app/build/test-results/
            android/app/build/reports/androidTests/

      - name: Upload test reports
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Android Test Results
          path: |
            android/app/build/test-results/test*/TEST-*.xml
            android/app/build/test-results/testDebugUnitTest/TEST-*.xml
          reporter: java-junit
          fail-on-error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Nuxt project
        run: npm run generate

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Run Android Lint
        run: ./android/gradlew lintDebug
        working-directory: .

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-results
          path: android/app/build/reports/lint-results-debug.html