name: Publish Test App

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'ios/**'
      - 'readme.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: install dependencies
        run: npm ci

      - name: build Nuxt project
        run: npm run generate

      - name: copy to Android project
        run: npx cap sync

      - name: build Android app
        run: ./android/gradlew assembleDebug -p android --no-daemon

      - name: rename apk
        working-directory: android/app/build/outputs/apk/debug/
        run: |
          build="$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short HEAD)"
          name="audiobookshelf-${build}.apk"
          mv -v app-debug.apk "${name}"

      - name: prepare test page ressources
        run: |
          # Create the deployment directory
          mkdir ghpages
          
          # Copy test app files
          cp android/app/build/outputs/apk/debug/*apk ghpages/
          cp static/Logo.png ghpages/logo.png
          cp .github/testing-page-template.html ghpages/index.html
          
          # Preserve existing documentation from the docs directory
          if [ -d "docs" ] && [ "$(ls -A docs)" ]; then
            echo "Copying documentation from docs directory..."
            cp -r docs/* ghpages/
          else
            echo "No documentation found in docs directory."
          fi
          
          # List the contents of the deployment directory
          echo "Contents of ghpages directory:"
          ls -la ghpages/

      - name: build test page
        working-directory: ghpages
        run: |
          sed -i "s/__DATE__/$(date)/g" index.html
          sed -i "s/__COMMIT__/$(git rev-parse --short HEAD)/g" index.html
          sed -i "s/__APK__/$(ls *apk)/g" index.html
          
          # Create a README.md file to explain the GitHub Pages deployment
          cat > README.md << EOF
# TomeSonic GitHub Pages

This directory contains:
1. The latest test build of the TomeSonic app
2. Documentation for the TomeSonic project

## Test Build

The latest test build is automatically generated from the master branch. This is intended for testing purposes only.

## Documentation

The documentation in this directory is preserved during deployments and includes:
- Privacy Policy
- Feature Graphics Template
- Other documentation files from the \`/docs\` directory

Last updated: $(date)
Commit: $(git rev-parse --short HEAD)
EOF

      - name: upload test page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ghpages

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
